jcmoraisjr/haproxy-ingress

rootfs/start.sh
/bin/sh points to bash in the alpine base image, but is usually a symlink to dash on other distros. This replaces bash-only substring expansion with a dash-compatible version.
=> Replace bash-only substring expansion

pkg/controller/controller.go, pkg/utils/utils.go, rootfs/haproxy-reload.sh
This works for native reload strategy. For multibinder reload strategy all configuration files are now kept in sync but validation is not performed as it cannot pass in a standalone haproxy process due to file-descriptor use.
As always, open for discussion.
=> verify new configuration is valid before replacing

pkg/controller/config.go, pkg/types/types.go, rootfs/etc/haproxy/template/haproxy.tmpl, rootfs/start.sh
This enables external load balancers, e.g. AWS ELBs, to use the proxy protocol on requests to haproxy-ingress.
=> Add use-proxy-protocol option

pkg/controller/stats_socket.go
This fixes a corner-case when if only some but not all socket commands fail, the successful ones would overwrite the previous value of `reloadRequired`.
=> fix reloadRequired potentially not set correctly

README.md, pkg/controller/config.go, pkg/types/types.go, rootfs/etc/haproxy/template/haproxy.tmpl
expose `http-log-format` and `tcp-log-format` to set the `log-format` on the respectively.
=> expose http and tcp log format

pkg/controller/template.go, rootfs/etc/haproxy/template/haproxy.tmpl
I added support for using a regex to allow *. wildcard hostnames.  This also escapes characters that are not allowed in ACL rules to an `_`. 
An example ishost rule will look like this: `ishost-_.example.com hdr_reg(host) ^([^\.]+)\.example.com`
=> add support for wildcard hostnames

rootfs/etc/haproxy/template/haproxy.tmpl
Fixes: #52
Replace variable that detects usage of client certificate from `ssl_fc_has_crt` to `ssl_c_used`.
=> Fix handling error496

rootfs/etc/haproxy/template/haproxy.tmpl
Some applications requires a X-Forwarded-Proto header when the reverse
proxy offloads SSL.
By adding "http-request set-header X-Forwarded-Proto https", the header
will be added if none exist, or it will replace previous occurences if
it was already present.
=> Add an X-Forwarded-Proto header in https frontends

README.md, pkg/controller/config.go, rootfs/etc/haproxy/template/haproxy.tmpl
#55 
Adds support for ingress annotation: `ingress.kubernetes.io/rewrite-target`.
Our test case for this work was `ingress.kubernetes.io/rewrite-target: /` as that has been the most common use case for us internally. This implementation SEEMS to be feature similar to the current implementation in the [kubernetes/ingress](https://github.com/kubernetes/ingress) nginx ingress controller, but our test cases were rather limited so unsure.
Used https://gist.github.com/kushmansingh/47644ef4db96f11b1ea450ae19072552 to do our testing but could have used most any other container that echoes the headers.
=> Add support for rewrite-target annotation

pkg/controller/stats_socket.go
The Endpoint address copied to FullSlots was a local variable re-used by a loop. This was resulting in all of the endpoints pointing to the last one copied.
Issue: #84
=> Correctly copy Endpoints to FullSlots

README.md, pkg/common/ingress/annotations/sessionaffinity/main.go, pkg/common/ingress/annotations/sessionaffinity/main_test.go, pkg/common/ingress/controller/annotations_test.go, pkg/common/ingress/controller/controller.go, pkg/common/ingress/types.go, pkg/common/ingress/types_equals.go, rootfs/etc/haproxy/template/haproxy.tmpl, tests/manifests/configuration-c.json
This is an additional annotation that will allow the user to select a different HAProxy cookie strategy other than insert. Supported additions are prefix and rewrite.
=> Add a cookie strategy

pkg/controller/controller.go
- Under high load situations (hundreds of services, certs, and ingress rules), we have seen infrequent but consistent cases of haproxy not reflecting the on-disk config file. One theory is a race condition on new haproxy processes pointing to an ever-changing config file. This commit gives each haproxy process its own config file that does not change. Not only should this remove the risk of loading a partially written file, it will also help debug the issue because we see a snapshot of the config used for each haproxy process.
- Config files are left on disk up to a max threshold, configurable via environment variable, to allow debugging issues.
- Not supported under with reloadStrategy=multibinder since multibinder-haproxy-wrapper currently only supports receiving a USR2 signal to reload …
=> Changes to support debugging haproxy reload not loading correct config

rootfs/etc/haproxy/template/haproxy.tmpl
Update haproxy.tmpl to accept http2 and http 1.1 connections.
Allow H2 connections to be accepted in addition to HTTP 1.1 connections.
Information about HAProxy 1.8 HTTP 2 support is available [here](https://www.haproxy.com/blog/whats-new-haproxy-1-8/).
A very small change providing nice performance wins.
=> Add support for Http 2 connections

Godeps/Godeps.json, README.md, pkg/common/ingress/controller/controller.go, pkg/common/ingress/controller/launch.go, pkg/common/ingress/controller/listers.go, pkg/common/ingress/store/main.go, pkg/common/ingress/types.go, pkg/common/ingress/types_equals.go, pkg/controller/config.go, pkg/controller/controller.go, pkg/controller/stats_socket.go, pkg/types/types.go, rootfs/etc/haproxy/template/haproxy.tmpl, vendor/k8s.io/kubernetes/pkg/kubelet/apis/BUILD, vendor/k8s.io/kubernetes/pkg/kubelet/apis/well_known_annotations.go, vendor/k8s.io/kubernetes/pkg/kubelet/apis/well_known_labels.go, vendor/k8s.io/kubernetes/pkg/util/node/BUILD, vendor/k8s.io/kubernetes/pkg/util/node/node.go
When a pod starts terminating or the readiness check fails, leave the pod as a service
in the load balancer, but set its weight to 0 so that HAProxy does not send ordinary
traffic to the pod. Traffic using persistence, however, will be directed to the terminating
pods. This allows persistent requests to continue to flow to a terminating pod. Updates to
only the draining state are made using the stats socket rather than forcing a full reload
of HAProxy.
This PR includes the described change, as well as a few fixes for typos I found along the way, and clearing up some warnings IntelliJ was showing (e.g., initializing slices with empty literal instead of nil, error messages starting with a capital letter).
I have a use case for pods having a long termination period and new requests with a …
=> Support a "drain" mode for terminating pods and servers failing readiness checks

pkg/common/ingress/types_equals.go, pkg/common/utils/utils.go, pkg/common/utils/utils_test.go, pkg/controller/stats_socket.go, pkg/types/equal.go
Changing the implementation of equality and partial equality of ingress config structs
* Changes are related with `dynamic-scaling` and `drain-support`
* Remove changing comparison of `Endpoint.Target` field
* Move from `DeepEqual` to `.Equal` func on ingress config struct, removing issues with internal states of k8s objects and unsorted arrays
* Usage of a cloned object `configCopy` for partial equality on behalf of visibility of what isn't being compared
* A new func `DeepEqualUnsorted` used to compare unsorted arrays
=> Change equality of drain-support and dynamic-scaling

pkg/controller/stats_socket.go
This changes the condition used to reload the server because of resizing of the backend slots. If the slots need to be shrinked the reload is skipped. They will be shrinked anyway if the server need to be reloaded for any other reason.
=> Avoid reload when shrinking backend slots

pkg/common/ingress/controller/backend_ssl_test.go, pkg/common/ingress/controller/launch.go, pkg/common/ingress/types.go, pkg/common/net/ssl/ssl.go, pkg/common/net/ssl/ssl_test.go, pkg/controller/config.go, pkg/controller/controller.go, pkg/controller/template.go, pkg/types/types.go, rootfs/etc/haproxy/template/haproxy.tmpl
Refactor of http/s frontends without client-cert auth into a single frontend, one http socket and one https socket.
This change is backward compatible with all current features.
bind :443 is still on tcp mode in order to sslpassthrough and client-cert auth to work.
The way HAProxy choose the backend changed: now the sni extension is only used to select which certificate should be used in the handshake. After the ssl-offload the `Host` header is used to select the backend, because of that `use-host-on-https` configmap option is now obsolete and will be removed.
=> Share http/s connections on the same frontend/socket

README.md, pkg/controller/controller.go, rootfs/Dockerfile, rootfs/haproxy-reload.sh, rootfs/start.sh
GitHub's multibinder [isn't compatible with HAProxy 1.8](https://github.com/github/multibinder/issues/15). Since the new `-x` HAProxy command-line option uses the same strategy - reusing the same sockets between old and new HAProxy process, `multibinder` is being deprecated and removed on behalf of `reusesocket` reload-strategy. If the user points the reload-strategy to multibinder, he will be warned (logs) and reusesocket will be used instead.
=> Remove multibinder, change it to an alias of reusesocket

rootfs/etc/haproxy/template/haproxy.tmpl
This applies the same `maxconn` settings to each proxy in addition to
the global `maxconn` setting.
Could fix https://github.com/jcmoraisjr/haproxy-ingress/issues/114
=> Add maxconn to defaults as well as global

README.md, pkg/controller/config.go, pkg/types/types.go, rootfs/etc/haproxy/template/haproxy.tmpl
Add `timeout-stop` configmap option - time to wait for long lived connections to finish before perform a hard-stop.
=> Timeout stop configmap option

pkg/controller/config.go, pkg/controller/template.go, pkg/types/types.go, rootfs/etc/haproxy/template/haproxy.tmpl
Give precedence on hosts without wildcard and alias without regex.
Implements #147.
=> Fix precedence on hosts/alias without regexp

README.md, pkg/common/ingress/annotations/cors/main.go, pkg/common/ingress/controller/annotations_test.go, pkg/controller/config.go, pkg/types/types.go, rootfs/etc/haproxy/template/haproxy.tmpl, rootfs/usr/local/etc/haproxy/lua/send-response.lua
Add CORS headers.
Implements #111
=> CORS headers

pkg/common/ingress/annotations/ipwhitelist/main.go, pkg/common/ingress/annotations/ipwhitelist/main_test.go, pkg/common/ingress/annotations/ratelimit/main.go, pkg/common/net/ipnet.go, pkg/common/net/ipnet_test.go
Changes how CIDR list used on whitelists (source and ratelimit) are built. Now if a whitelist annotation has invalid CIDRs, at least the valid CIDRs will be applied. Before this PR the whitelist configuration would be removed.
Fix #86
=> Add valid CIDRs on whitelists

rootfs/etc/haproxy/template/haproxy.tmpl
ACLLabel is not expected to be here.
This commit (a80d2c648369c7a58ae32cc278e9d8cbbb588669) breaks the `ingress.kubernetes.io/ssl-passthrough` annotation.
/milestone v0.6
/label fix
=> Fix ssl-passthrough annotation

rootfs/etc/haproxy/template/haproxy.tmpl
Fix redirect-https if used with rewrite-target.
Option 1 (current): use an acl so reqrep will only execute if redirect https isn't executed
Option 2: write the whole new location using `txn.path` instead of redirect https
Fixes #178 .
=> Fix redirect https if path changed with rewrite-target

pkg/controller/config.go, pkg/types/types.go, rootfs/etc/haproxy/template/haproxy.tmpl
=> Add wildcard hostnames on SSL passthrough config

README.md, pkg/controller/config.go, pkg/types/types.go, rootfs/etc/haproxy/template/haproxy.tmpl
On some haproxy-ingress setups several instances of haproxy can coexists
on same node, to avoid port mapping clashes, add configuration options
to allow change ports
=> Add http/https port map configuration

pkg/common/ingress/controller/backend_ssl.go, pkg/common/ingress/controller/backend_ssl_test.go, pkg/common/ingress/controller/controller.go
Change the responsibility of `getPemCertificate` in order to know that err is a parsing failure and not a secret not found. A parsing failure means that the secret isn't a ca/crt and should sync; a secret not found should not.
=> Fix endless loop if SSL/TLS secret does not exist

README.md, pkg/common/ingress/controller/controller.go, pkg/common/ingress/types_equals.go, pkg/controller/config.go, pkg/types/equal.go, pkg/types/types.go, rootfs/etc/haproxy/template/haproxy.tmpl
A new configmap option to enable SSL on stats page.
Implements #180
=> Add stats-ssl-cert configmap option

README.md, rootfs/etc/haproxy/template/haproxy.tmpl
Check if `backend-check-interval` configmap option is empty, if so, disable health check of the backends.
=> Option to disable health check of the backends

README.md, pkg/controller/config.go, pkg/types/types.go, rootfs/etc/haproxy/template/haproxy.tmpl
A new configmap option to add configuration snippet on HAProxy http frontend sections.
Implements #118 and #188
=> Add config-frontend configmap option

README.md, pkg/common/ingress/controller/controller.go, pkg/common/ingress/types.go, pkg/common/ingress/types_equals.go, rootfs/etc/haproxy/template/haproxy.tmpl
Add secret name on tcp-service configmap. The secret name should have a crt/key pair used to ssl-offload TCP requests.
Implements #126 .
=> Add SSL/TLS config on TCP services

README.md, examples/modsecurity/README.md, examples/modsecurity/agent-daemonset.yaml, pkg/common/ingress/annotations/waf/main.go, pkg/common/ingress/controller/annotations.go, pkg/common/ingress/types.go, pkg/common/ingress/types_equals.go, pkg/controller/config.go, pkg/controller/template.go, pkg/types/types.go, rootfs/etc/haproxy/spoe-modsecurity.conf, rootfs/etc/haproxy/template/haproxy.tmpl
Add config options to a ModSecurity web application firewall agent (SPOA).
=> ModSecurity WAF

README.md, pkg/controller/config.go, pkg/types/types.go, rootfs/etc/haproxy/template/haproxy.tmpl
Add new configmap options to support multi process and/or multi thread configuration.
* `nbproc-ssl`: number of processes dedicated to ssl-offloading; plain http requests are handled on another dedicated process.
* `nbthread`: number of threads for each process.
Todo:
=> Add multi process and multi thread support

rootfs/etc/haproxy/template/haproxy.tmpl
Change rate limit check from tcp to http in order to match the host header. This will also change the response, from closing the connection with an empty reply to http 403 status code.
=> Fix host match of rate limit on shared frontend

rootfs/Dockerfile
Add the directory `/ingress-controller` because in OpenShift can't the pod create the root dir
fix #205
=> Add /ingress-controller

pkg/common/net/ssl/ssl.go
Move dh-param file outside the ssl dir. Since v0.6, all pem files from the ssl dir are used on the frontend's ssl config.
=> Fix ssl-dh-param option

README.md
I am running v0.6-beta.3 in AWS, k8s 1.9 and external-dns. It is perfectly working. I hope were in the documentation to save time the next person. 👍 
Related to this issue https://github.com/jcmoraisjr/haproxy-ingress/issues/93
=> Add publish-service documentation

pkg/common/ingress/controller/controller.go
As default http/https ports can be overriden by ConfigMap
remove them from reserved
=> Remove ports 80/443 from reserved

pkg/controller/config.go
The SSL test is [capped at B](https://www.ssllabs.com/ssltest/analyze.html?d=janco-it.de) with the default settings. Changing dh-param in the configmap to `2048` [results in an A+](https://www.ssllabs.com/ssltest/analyze.html?d=cerberus-systems.com)
=> Change dh param size

README.md, pkg/controller/config.go, pkg/types/types.go, rootfs/etc/haproxy/template/haproxy.tmpl
This configmap option defines whether another matching host/FQDN should be visited in order to match the path of a request.
Implements #157
=> Add strict-host configmap option

pkg/common/net/ssl/ssl.go, pkg/controller/config.go, rootfs/etc/haproxy/template/haproxy.tmpl
A small improvement on v0.7 after adding client cert for backends. All crt/key pairs are added to the ssl directory. This PR create a new `+default.pem` file with all and only the crt/keys that should be used in the shared frontend.
This will change again on v0.8 after create an array of frontends, each one with their array of servers/crt/key.
=> Use a multi pem file instead the ssl dir on shared frontend

README.md, pkg/common/ingress/annotations/secureupstream/main.go, pkg/common/ingress/annotations/secureupstream/main_test.go, pkg/common/ingress/controller/annotations_test.go, pkg/common/ingress/controller/controller.go, pkg/common/ingress/resolver/main.go, pkg/common/ingress/types.go, pkg/common/ingress/types_equals.go, rootfs/etc/haproxy/template/haproxy.tmpl, tests/manifests/configuration-a.json, tests/manifests/configuration-b.json, tests/manifests/configuration-c.json
Add annotation `ingress.kubernetes.io/secure-crt-secret` to provide a client cert on TLS connections to backend.
Implements #177
=> Add client cert auth for backend

README.md
As documented in https://github.com/jcmoraisjr/haproxy-ingress/issues/210, we were seeing the DH parameter configuration spam our logs. This turned out to be an issue with our configuration where we included the certificate in the `ssl-dh-param` instead of having it reference a secret with that data. 
This documentation PR hopes to help others from making the same mistake by providing an example of the secret and specifying that the secret should be referenced in your haproxy-ingress configuration.
=> Update ssl-dh-param documentation for clarity

README.md
The documentation (README.md) states that the secret used for TLS client certificate authentication requires a key named `ca` containing the certificate data, when in fact it [needs to be `ca.crt`](https://github.com/jcmoraisjr/haproxy-ingress/blob/ab62cfe38c8766a00a261fc590523e9f0400fc9d/pkg/common/ingress/controller/controller.go#L580).
I'm doing some testing with client certificates at the moment.
=> Fix documentation for auth-tls client

rootfs/Dockerfile
The upstream image is used to start HAProxy itself as pid1. Its stop signal was changed to SIGUSR1 which does a soft reload on HAProxy. Our pid1 is the controller which only listen SIGTERM (docker stop) and SIGINT (^C).
Changing the stop signal in the container image as a way to document what the controller process is expecting.
=> Fix stop/terminate signal of the controller process

pkg/controller/config.go, rootfs/etc/haproxy/template/haproxy.tmpl
Template trust only in the SSLRedirect attribute to configure the redirect itself and the URL rewrite.
So turn SSLRedirect off despite of its original configuration if the server doesn’t have a certificate.
Revert #231
Related with #229
=> Fix SSL redirect if no TLS config is used

pkg/common/net/ssl/ssl.go, pkg/controller/config.go, rootfs/etc/haproxy/template/haproxy.tmpl
A single HAProxy frontend can handle several domains using a single `bind` keyword and a single `crt` configuration. This change create a directory that receives (hard link) all certificates used on the shared frontend.
This will change again on v0.8 after create an array of frontends, each one with their array of servers/crt/key.
Fixes #223
=> Add per directory TLS configuration of shared frontend

README.md, pkg/common/ingress/annotations/balance/main.go, pkg/common/ingress/annotations/connection/main.go, pkg/common/ingress/annotations/proxy/main.go, pkg/common/ingress/annotations/waf/main.go, pkg/controller/config.go
Add validation on:
* balance algorithm annotation and configmap
* proxy body size annotation and configmap
* timeout queue
Implements #170
=> Add annotation and configmap validations

README.md, pkg/common/ingress/annotations/proxybackend/main.go, pkg/common/ingress/controller/annotations.go, pkg/common/ingress/controller/controller.go, pkg/common/ingress/types.go, pkg/common/ingress/types_equals.go, rootfs/etc/haproxy/template/haproxy.tmpl
Add `ingress.kubernetes.io/proxy-protocol` annotation for backends. Supported protocols are `v1`, `v2`, `v2-ssl`, `v2-ssl-cn`, falling back to not using the protocol if not specified.
=> Add proxy-protocol annotation

README.md, examples/auth/oauth/README.md, examples/auth/oauth/app.yaml, examples/auth/oauth/oauth2-proxy.yaml, pkg/common/ingress/annotations/oauth/main.go, pkg/common/ingress/controller/annotations.go, pkg/common/ingress/types.go, pkg/common/ingress/types_equals.go, pkg/controller/config.go, pkg/types/types.go, rootfs/Dockerfile, rootfs/etc/haproxy/template/haproxy.tmpl, rootfs/usr/local/etc/haproxy/lua/auth-request.lua
Starting implementation of OAuth2 support. An oauth2 proxy should be configured as a deployment+service to make the OAuth handshake and sign a token. The current implementation uses Bitly’s `oauth2_proxy`.
Implements #200
=> Add OAuth2 support

README.md, pkg/common/ingress/annotations/sslpassthrough/main.go, pkg/common/ingress/annotations/sslpassthrough/main_test.go, pkg/common/ingress/controller/annotations.go, pkg/common/ingress/controller/annotations_test.go, pkg/common/ingress/controller/controller.go, pkg/common/ingress/types.go, pkg/common/ingress/types_equals.go, pkg/controller/config.go, pkg/types/types.go, rootfs/etc/haproxy/template/haproxy.tmpl, tests/manifests/configuration-a.json, tests/manifests/configuration-b.json, tests/manifests/configuration-c.json
New annotation `ingress.kubernetes.io/ssl-passthrough-http-port` used to configure an optional http port of a ssl-passthrough backend service. If http-port isn't provided, HAProxy will 302 redirect from http to https. If provided, requests to HAProxy http port, default `80`, will be sent to the specified port of the same service.
This is a useful configuration when HAProxy is transparently fronting another ingress controllers or loadbalancers.
=> Add http-port on ssl-passthrough

rootfs/etc/haproxy/template/haproxy.tmpl
Summary
The application is missing the 'httpOnly' cookie attribute
Vulnerability Detection Result
The cookies:
Set-Cookie: JSESSIONID=lGbJl57jz/c=; path=/ 
are missing the "httpOnly" attribute.
Solution
Solution type: Mitigation Mitigation
Set the 'httpOnly' attribute for any session cookie.
Affected Software/OS
Application with session handling in cookies.
Vulnerability Insight
The flaw is due to a cookie is not using the 'httpOnly' attribute. This allows a cookie to be accessed by JavaScript which could lead to session hijacking attacks.
Vulnerability Detection Method
Check all cookies sent by the application for a missing 'httpOnly' attribute
Details: Missing `httpOnly` Cookie Attribute (OID: 1.3.6.1.4.1.25623.1.0.105925)
Version used: $Revision: 5270 $
References
Other: …
=> added "httponly" for cookie affinity

pkg/controller/dynconfig/dynconfig.go, pkg/types/types.go, rootfs/etc/haproxy/template/haproxy.tmpl
Use a slice instead of map on backend lists in order to respect the order of the endpoints. Endpoints can be sorted or shuffled depending on command-line option.
Fixes #240
=> Fix sort-backends behavior

README.md, pkg/common/ingress/annotations/alias/main.go, pkg/common/ingress/annotations/alias/main_test.go, pkg/common/ingress/controller/annotations.go, pkg/common/ingress/controller/controller.go, pkg/common/ingress/types.go, pkg/common/ingress/types_equals.go, pkg/controller/config.go, pkg/controller/template.go, pkg/types/types.go, rootfs/etc/haproxy/template/haproxy.tmpl
Changing the behavior of server-alias:
* `server-alias-regex`: new annotation, used to match hostname with POSIX extended regular expression. The regex is used verbatim and the matching is case insensitive.
* `server-alias`: changed to mimic hostname behavior - accept wildcard hostnames and usage of regex is discouraged. The matching is also case insensitive.
Implements #246
=> Add server-alias-regex annotation

examples/auth/oauth/oauth2-proxy.yaml
The `quay.io/jcmoraisjr/oauth2-proxy` [Dockerfile](https://github.com/jcmoraisjr/oauth2-proxy/blob/1b85e2035fa3d45f705944b33c107b19d55d9c6b/Dockerfile#L5) adds the binary as /oauth2_proxy instead of oauth2-proxy:
```FROM alpine:3.8
ARG URL=https://github.com/bitly/oauth2_proxy/releases/download/v2.2/oauth2_proxy-2.2.0.linux-amd64.go1.8.1.tar.gz
RUN apk add --no-cache ca-certificates \
&& wget -O- $URL | tar xzf - --strip-components=1\
&& chown root.root /oauth2_proxy\
&& addgroup -g 1001 oauth2proxy\
&& adduser -u 1001 -G oauth2proxy -D -s /bin/false oauth2proxy
USER oauth2proxy
```
=> Fixed oauth2_proxy cmd arg

pkg/controller/config.go, pkg/types/types.go
SSL-passthrough configuration reuse acl template to build routes on SSL/TLS frontend. Currently ssl-passthrough doesn’t support alias annotations. This change implements some fields expected by the acl template
Fixes #257
=> Fix ssl-passthrough

README.md, rootfs/etc/haproxy/template/haproxy.tmpl
Signed-off-by: Ricardo Pchevuzinske Katz <ricardo.katz@serpro.gov.br>
Improve optional client cert auth. 
The following will happen:
* When the annotation `ingress.kubernetes.io/auth-tls-verify-client` is set to `optional` or `on`, the following validations will be made
* If the certificate is invalid, expired, not recognized by any CA configured as the `auth-tls-secret` the error 495 will be used (the customized one, or the default one)
* If the certificate isn't presented by the client and it's required, using the `auth-tls-verify-client: "on"` the error 496 will be used (the customized one, or the default one)
=> Improve optional client cert auth

README.md, pkg/controller/config.go, pkg/types/types.go, rootfs/etc/haproxy/template/haproxy.tmpl
Supported format from haproxy are : rfc5424 or rfc3164
I personally need this to make log forward work with filebeat which expect rfc3164 format rather than 5424 and currently print out errors like 
```
haproxy-ingress-7d59695959-q5sjc haproxy-beat 2019-01-07T13:35:02.759Z  ERROR   [syslog]        syslog/input.go:131     can't not parse event as syslog rfc3164 {"message": "<134>1 2019-01-07T13:35:02+00:00 haproxy-ingress-7d59695959-q5sjc ingress 44 - - 10.244.5.0:48548 [07/Jan/2019:13:35:02.165] httpfront-shared-frontend~ aaa-aaaa-web-staging-8000/10.244.13.99:8000 0/0/1/593/595 404 9085 - - ---- 4/2/1/1/0 0/0 \"GET /health/ HTTP/1.1\"\n"}
```
=> Add support to customize haproxy logformat

pkg/controller/controller.go
HAProxy reloads are done after creating or updating haproxy.cfg and modsec.cfg, but validation of haproxy.cfg is done just after writing it to disk. This change writes haproxy.cfg after modsec.cfg in order to successfully validate it.
Fixes #281
=> Fix validation of mod security conf

pkg/controller/config.go
`os.Mkdir` receives the directory permission as a three groups of three bits number. Usually such notation is used as an octal number which, in Go, starts with a zero that was missing here.
=> Fix permission of frontend certs dir

README.md, pkg/controller/config.go, pkg/types/types.go, rootfs/etc/haproxy/template/haproxy-v07.tmpl
ALPN advertisement configuration is used to choose the HTTP protocol version. By default h2 is used if the client has support, falling back to http/1.1 otherwise. This configmap option could be used if h2 has any issue with some clients.
=> Add TLS ALPN extension advertisement

pkg/controller/config.go, rootfs/etc/haproxy/template/haproxy-v07.tmpl
An overlap happens whenever a `/path` of a domain has a configuration, eg whitelist or body-size limit, and a `/path/sub` doesn’t have such configuration. Most of match is made with path_beg which will also match the subpath uri. This change adds a `!{ subpath }` acl to fix this behavior.
=> Fix overlapping configs on shared frontend

rootfs/Dockerfile
HAProxy emits a SIGSEGV and fails to start or check a valid configuration with new certificate authority bundles. Updating libssl and libcrypto to 1.1.1b fixes this.
=> Update libssl and libcrypto

README.md, pkg/controller/config.go, pkg/converters/ingress/annotations/updater.go, pkg/converters/ingress/defaults.go, pkg/converters/ingress/types/config.go, pkg/haproxy/types/types.go, pkg/types/types.go, rootfs/etc/haproxy/template/haproxy-v07.tmpl, rootfs/etc/haproxy/template/haproxy.tmpl
This fixes an issue where drain-support would lock a cookie affinity to a backend pod, even after it was terminated. Enabling `redispatch` as per haproxy doc recommendations fixes this to redispatch the session once the target pod is finally shutdown.
Without this change, haproxy returns a 503 status until a new session is started by the user.
Reference from haproxy: https://cbonte.github.io/haproxy-dconv/1.7/configuration.html#4-option%20persist
=> Enable redispatch even when drain-support is enabled

rootfs/Dockerfile
Upgrade to HAProxy 1.8.20.
This PR also remove a temporary upgrade of libssl and libcrypto from 1.1.1a to 1.1.1b - the Alpine base image has already the 1.1.1b version. 1.1.1a causes HAProxy to emit SIGSEGV and fail to start or check a valid configuration with some new certificate authority bundles.
=> Upgrade to HAProxy 1.8.20

README.md, pkg/controller/config.go, pkg/converters/ingress/annotations/global.go, pkg/converters/ingress/defaults.go, pkg/converters/ingress/types/config.go, pkg/haproxy/types/types.go, pkg/types/types.go, rootfs/etc/haproxy/template/haproxy-v07.tmpl, rootfs/etc/haproxy/template/haproxy.tmpl
Allows additional values to be specified in the HAProxy "defaults" section by putting them in a multi-line snippet in the configmap.
=> Add configmap snippet for defaults.

rootfs/etc/haproxy/template/haproxy-v07.tmpl
This fixes an issue where any frontend configuration is duplicated twice for the default backend.
Example for a `config-frontend` in the ConfigMap of `http-response add-header my-header` results in two headers `my-header` in the response from the default backend.
This is particularly bad when forcing http to https redirection using `config-frontend` we were seeing an infinite loop of redirects for unknown ingress endpoints rather than a 404.
=> Fix duplication of ConfigFrontend snippets for DefaultBackend

pkg/converters/ingress/annotations/backend.go, pkg/converters/ingress/annotations/backend_test.go, pkg/converters/ingress/annotations/global.go, pkg/converters/ingress/annotations/global_test.go, pkg/haproxy/instance.go, pkg/haproxy/instance_test.go, pkg/utils/utils.go, rootfs/etc/haproxy/template/haproxy.tmpl
Some small fixes before snapshot.2:
Related with #339 
Implements #274
=> New ingress converter and haproxy types (part 4)

rootfs/etc/haproxy/template/haproxy-v07.tmpl, rootfs/etc/haproxy/template/haproxy.tmpl
> port of https://github.com/jcmoraisjr/haproxy-ingress/pull/354 to master
When CORS is enabled on a k8s ingress definition that also has Basic Auth, the connection from a browser fails because the browser (correctly) does not send the Basic Auth credentials on the pre-flight OPTIONS request.
Example annotations to recreate:
```yaml
ingress.kubernetes.io/auth-realm: Authentication Required
ingress.kubernetes.io/auth-secret: somesecret
ingress.kubernetes.io/auth-type: basic
ingress.kubernetes.io/cors-allow-credentials: "true"
ingress.kubernetes.io/cors-allow-methods: POST,PUT,GET,DELETE
ingress.kubernetes.io/cors-allow-origin: '*'
ingress.kubernetes.io/enable-cors: "true"
```
This PR suggests updating the http-request auth rule to be disabled for OPTIONS requests when CORS is enabled on a …
=> Disable HTTP Basic Auth on CORS pre-flight OPTIONS request

README.md, pkg/common/ingress/controller/controller.go, pkg/common/ingress/controller/launch.go, pkg/controller/controller.go
I've encountered a case, when deploying haproxy ingress controller with helm chart and some changes in Deployment object (which already had terminationGracePeriodSeconds as 4 minutes), my controller's Pods once received SIGTERM, shut down themselves almost immediately, causing the connections to be broken.
I'd like to propose a parameter of --terminate-grace-period defined as integer of seconds, which causes the Stop function to wait defined time before it shuts down the controller's components. Thanks to this, if terminationGracePeriodSeconds and --terminate-grace-period are defined, long living connections might have a chance to complete, while the Pod is taken of out Service's endpoints, so no new requests are coming.
=> Add --wait-before-shutdown flag to wait defined time when SIGTERM received

rootfs/etc/haproxy/template/haproxy-v07.tmpl
The modsecurity backend is referenced by the spoe configuration file, so the automatic binding of that backend to the balance processes does not work when nbproc is declared. This change configures the modsecurity backend to the right processes.
v07 controller only.
=> Bind modsecurity backend to balance process

pkg/converters/ingress/annotations/updater.go, pkg/converters/ingress/types/annotations.go
A HAProxy var txn.namespace can be configured with the k8s namespace owner of the service which is the target of the request. This can be used on http logs. var-namespace is a boolean annotation that defaults to false, which means txn.namespace shouldn't be created.
This change only defines the annotation. The haproxy entity was already implemented.
=> Add var-namespace annotation

pkg/converters/ingress/ingress.go, pkg/converters/ingress/ingress_test.go, pkg/converters/utils/services.go
Terminating pods are used on DrainSupport mode. They don't have endpoints so need their own func to find the correct container port if a named port is being used.
The service's target port should be a valid port number, which means it is the container port number, or should be a valid named port declared in the container. If the port is nether a valid number nor a declared named port, the endpoint of that pod will not be added.
=> Fix port number lookup of terminating pods

pkg/haproxy/instance_test.go, rootfs/etc/haproxy/template/haproxy.tmpl
The sni extension is mandatory if a client certificate authentication is used. However, if the certificate is optional, the request was falling back to the default backend if sni isn't provided.
This commit changes how requests to domains protected by authentication via client cert works: if a client certificate is optional and the request does not provide one, the host header will be used to match a backend. If a certificate is mandatory or a certificate is sent, the sni extension continue to be mandatory and will be used instead.
This should be merged to v0.8.
=> Make sni optional if a certificate is optional and is not provided

pkg/haproxy/instance_test.go, rootfs/etc/haproxy/template/haproxy.tmpl, rootfs/usr/local/etc/haproxy/errors/421.http
Browsers reuse a stablished TLS connection if a wildcard or multi DNS certificate matches more than one domain. This is a problem if the new request uses client cert authentication, whose validation happens on the TLS handshake.
A 421 HTTP response makes the browser create a new TLS connection. This response will be used if the sni extension (from the TLS handshake) and the host header (from the request) does not match.
* https://www.mail-archive.com/haproxy@formilux.org/msg29789.html
* https://www.mail-archive.com/haproxy@formilux.org/msg33799.html
=> Use 421 response if sni and headers does not match

README.md, pkg/common/ingress/controller/backend_ssl.go, pkg/common/ingress/controller/controller.go, pkg/common/ingress/controller/launch.go, pkg/common/ingress/resolver/main.go, pkg/common/ingress/sort_ingress.go, pkg/common/ingress/types.go, pkg/common/net/ssl/ssl.go, pkg/common/net/ssl/ssl_test.go, rootfs/etc/haproxy/template/haproxy-v07.tmpl
Added an additional check for ca.crl in the TLS secret, and storing the
provided PEM file separately allowing the HAproxy server to verify a
client certificate being used has not been revoked.
=> Add CRL Support in the TLS Secret for Client Authentication

pkg/controller/controller.go
Ingress objects can overlap each other configurations - two or more ingress can compose a single domain/hostname with distinct backend/service configurations. This is fine.
HAProxy Ingress does its best to merge objects and configurations in order to make a consistent state. However if conflicting configuration is used to the same entity, a warning is logged and one of the configurations should be used.
Before the current change, the ResourceVersion was being used to sort ingress objects, which means that the object updated earlier wins. This could sound good but the ResourceVersion is unique to the whole object, which means an old configuration of a just updated object would be overridden by a conflicting configuration of another object, changing the cluster status in a wrong way. This …
=> Sort ingress using creation timestamp

docs/haproxy-ingress.yaml
Kubernetes version 1.16 has removed several deprecated APIs that you'll likely recognize and may use on a daily basis
=> Kubernetes version 1.16 removed several deprecated APIs

docs/content/en/docs/configuration/keys.md, pkg/converters/ingress/defaults.go, pkg/haproxy/dynupdate.go, pkg/haproxy/dynupdate_test.go, pkg/haproxy/instance_test.go
Dynamic update was always running despite `dynamic-scaling` configuration. The current behaviour doesn't change, its default value was `true` since v0.8 and will continue to be.
This should be merged to v0.8.
=> Add dynamic-scaling false option

pkg/controller/controller.go, pkg/haproxy/config.go
Configuration change is mostly performed on diff'ing old and new internal state, because of that all internal slices should be sorted.
This change improves two scenarios:
* Order of ingress with the same creation timestamp wasn't idempotent, added a fallback to namespace/name
* Users of a userlist wasn't sorted
=> Improve sorting of internal state

docs/content/en/docs/configuration/command-line.md, docs/content/en/docs/configuration/keys.md, pkg/controller/controller.go, pkg/converters/ingress/defaults.go
Upgrading the default thread number to 2 (two) and reload strategy to reusesocket (hitless reloads, haproxy's `-x`).
This should be merged to v0.8.
=> Tuning default thread number and reload strategy

pkg/haproxy/instance_test.go, rootfs/etc/haproxy/template/haproxy.tmpl
Request match are made case insensitive converting incoming data and map files to lowercase. This fixes a request match in the backend side used by per-path requests, eg whitelist, hsts, cors and others.
=> Fix case on per-path backend requests

pkg/controller/cache.go, pkg/controller/controller.go, pkg/controller/leaderelection.go
A leader elector is used to select which ingress-controller instance should perform operations that should be done just once - by the leader. A configmap object in the k8s cluster is used to control which instance is the leader.
Use cases:
* status update: the status of the ingress object should be updated by only one instance
* acme signer: sign of new certificates should be done by only one instance
The old controller has its own leader elector to update ingress status. That leader elector will be deprecated before v0.9-beta.
=> Add leader election

pkg/controller/cache.go, pkg/controller/controller.go, pkg/converters/configmap/tcpservices.go, pkg/converters/helper_test/cachemock.go, pkg/converters/ingress/annotations/backend.go, pkg/converters/ingress/annotations/global.go, pkg/converters/ingress/annotations/host.go, pkg/converters/ingress/ingress.go, pkg/converters/ingress/ingress_test.go, pkg/converters/ingress/utils/utils.go, pkg/converters/types/interfaces.go
`--allow-cross-namespace` command-line option wasn't ported to the v0.8 controller. It defaults to `false` which blocks the reading of any secret from one namespace to populate configurations of another namespace.
Should be merged to v0.8
related with #429
=> Add cross-namespace command-line option

pkg/haproxy/instance_test.go, rootfs/etc/haproxy/template/haproxy.tmpl
Request processing are made using the `base` sample (host+path) and sometimes only the Host header is used. Some http clients add the port number in the header, giving something like `domain.local:80` where only the `domain.local` part should be used to match ingress hostnames. This conversion is done using regsub() that matches and removes `:[0-9]+/`. The problem here is the trailing slash: it only exists in the `base` sample and doesn't exist if the host header is used.
Should be merged to v0.8
=> Fix host match with a port number

pkg/utils/queue.go, pkg/utils/queue_test.go
A work queue is used to start workloads asynchronously. The workload itself always run once at a time.
Use cases:
* parsing ingress: the ingress parser and config builder is a workload which runs when the k8s state changes
* acme signer: a v0.9 feature, sign a new certificate is a workload which runs when a new certificate need to be issued
Progress:
=> Add work queue

docs/content/en/docs/configuration/keys.md, pkg/converters/ingress/annotations/global.go, pkg/converters/ingress/annotations/global_test.go, rootfs/etc/haproxy/template/haproxy.tmpl
Add the new option `update` to forwardfor global configuration key. This option updates any provided `X-Forwarded-For` header without removing the original content.
=> Add forwardfor option - update

docs/content/en/docs/configuration/keys.md
The defaults for cors-allow-methods and cors-allow-credentials were swapped in the docs.
=> docs: defaults for cors-allow-methods and -headers

docs/content/en/docs/configuration/keys.md, pkg/converters/ingress/annotations/backend.go, pkg/converters/ingress/annotations/backend_test.go, pkg/converters/ingress/defaults.go, pkg/converters/ingress/types/annotations.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/backend.go, pkg/haproxy/types/types.go, rootfs/etc/haproxy/template/haproxy.tmpl
Signed-off-by: Ricardo Pchevuzinske Katz <ricardo.katz@serpro.gov.br>
This PR adds support for a DetectionOnly mode in Mod Security for each backend.
The idea here is when specifying the annotation 'waf-mode: "DetectionOnly"' it will send the requests to the ModSecurity filter to generate the appropriate logging, but no action will be taken.
To keep the compability with following versions, the behavior here is: if there's a ``waf`` annotation and no ``waf-mode`` annotation, it will block bad requests.
To enable DetectionOnly mode user must create the ``waf-mode`` annotation with DetectionOnly as its value
=> Add support for Mod Security DetectionOnly Mode

docs/content/en/docs/configuration/keys.md, pkg/converters/ingress/annotations/backend.go, pkg/converters/ingress/annotations/backend_test.go, pkg/converters/ingress/defaults.go, pkg/converters/ingress/ingress.go, pkg/converters/ingress/ingress_test.go, pkg/converters/ingress/types/annotations.go, pkg/haproxy/config.go, pkg/haproxy/dynupdate_test.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/backend.go, pkg/haproxy/types/types.go, rootfs/etc/haproxy/template/haproxy.tmpl
The `initial-weight` configuration key defines the static weight configuration of each backend server, which will define the initial weight configuration. The initial weight configuration is used on agent-check: an agent can change the weight of a server defining a percentage value of the initial weight.
Without this option, servers always start with weight 1 (one) and empty slots start with weight 0 (zero). If trying to update the weight via agent, in the former, the weight cannot be downgraded without removing the server from the balance, and the upgrade is always at least duplicating the weight. In the latter the weight cannot be changed. Iow weight via agent cannot be used.
Should be back ported to v0.8.
Related with #442
=> Add initial-weight config key

docs/content/en/docs/configuration/keys.md, pkg/converters/ingress/annotations/global.go, pkg/converters/ingress/types/global.go, pkg/haproxy/config.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/global.go, rootfs/etc/haproxy/template/haproxy.tmpl
Fixes https redirect scheme and port sharing with http-port, which defaults to 80. Name changed from `https-to-http-port` to `fronting-proxy-port` which better represents the functionality. The old name is now an alias to the new one.
The implementation was moved from https frontend to http due to some advantages:
* Easier to share the same http port without side effect
* There is less `if`s in the http frontend if compared to the https one
Missing var-namespace and max-body-size implementations which wasn't in the http frontend.
Should be merged to v0.8.
Related with #401
=> Improve fronting proxy config

pkg/controller/controller.go
Leader election is used only on acme and status update, which aren't implemented yet in the new controller. This change removes its initialization.
=> initialize leader election only if needed

docs/content/en/docs/configuration/keys.md, pkg/converters/ingress/annotations/global.go, pkg/converters/ingress/annotations/global_test.go, pkg/converters/ingress/types/global.go, pkg/haproxy/config.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/global.go, pkg/haproxy/types/types.go, rootfs/etc/haproxy/template/haproxy.tmpl
The current binding implementation configures IP/wildcard and port number using distinct configuration keys. This limits the number of listening port and IP family haproxy should be listening per frontend. Listening eg both IPv4 and IPv6 cannot be done.
Should be merged to v0.8.
=> add ip+port bind support for http/https/fronting-proxy

pkg/haproxy/instance_test.go, rootfs/etc/haproxy/template/haproxy.tmpl
`concat()` converter was declared wrong in two ways: using the first argument which is a constant instead of a dynamic arg, and using a fetch sample instead of a var name. This commit fixes both.
There is also an improvement on sni parsing: a regex was being used to remove a possible port number after the domain name. This port number is a possibility in the Host header but it is not in the sni extension, so the regex was removed.
=> fix hostname match of domains with client cert auth

pkg/converters/utils/services.go, pkg/converters/utils/services_test.go
Endpoint's targetRef was being read without checking for nil value. A string targetRef version is optional and used eg on blue/green deployment. Using an empty string if nil is enough.
Should be merged to v0.8
=> fix panic reading empty targetRef from ep

pkg/haproxy/config.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/frontend.go, pkg/haproxy/types/types.go, rootfs/etc/haproxy/template/haproxy.tmpl
Requests on http frontend wasn't filling txn.namespace var. This haproxy var can be used in http logs to reference the k8s namespace owner of the ingress object which declares the domain and path of the request. The namespace mapping should also be changed to an internal global scope in order to have visibility from the http frontend.
This should be merged to v0.8.
=> fix txn.namespace on http requests

pkg/haproxy/config.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/host.go
Ingress.spec.tls declares hostnames/domains and an optional secret with crt+key used to ssl-offload https requests on that domains. If a secret name is not declared or is invalid, the default crt+key is used instead.
This commit fixes a misbehaviour when ssl-redirect is true, declared or inherited from configmap, without a TLS being declared. Now ssl-redirect only return 302 redirect if ingress.spec.tls declares the hostname/domain.
Should be merged to v0.8.
=> do ssl-redirect only if tls declares the hostname

pkg/haproxy/types/frontend.go
Backend config has a matching host+path map file used to partially apply ACLs. Some users of this map: hsts, waf and whitelist. While the host and path samples are being converted to lowercase since 8d69fa7, the entries in the map was not.
=> fix case on per-path backend maps

pkg/haproxy/instance_test.go, rootfs/etc/haproxy/template/haproxy.tmpl
The string `_nomatch` was used everywhere as a fallback if some pattern isn't found in a map. This used to work nice provided that the source sample could be found.
There is however a special use case when the sni extension isn't provided and the domain has optional client cert: the response is 404 due to the fetch sample failed. This doesn't affect v0.8 because the failed sample is new in v0.9 - see concat().
This change removes the default value on map*() converters, so it can fail, won't create the target variable and `-m found` can be used instead.
=> use the found match pattern

pkg/haproxy/instance_test.go, rootfs/etc/haproxy/template/haproxy.tmpl
We try hard to deliver the request if sni is missing (old http clients) or misconfigured (reusing a connection). This change fixes, enforces or improve the rules below:
- routing is always based on host header, except if the client certificate is mandatory or a client certificate is provided
- if a client certificate is provided, sni is mandatory and a http 421 is issued if it doesn't match the host header
- if sni is missing or doesn't match the host header, a client certificate should be optional or not requested at all, and if requested by the proxy, should not be provided by the client
- if the sni provided references a domain which doesn't request a certificate, or sni is not provided, the client certificate is ignored and the request will be routed as if it wasn't provided
=> improve response error on sni mismatch

rootfs/Dockerfile
installing dumb-init from alpine repo allows me to build Haproxy docker image on architecture different than amd64
minimizing number of docker stages
=> dumb-init added from alpine repo

pkg/haproxy/instance_test.go, rootfs/etc/haproxy/template/haproxy.tmpl, rootfs/usr/local/etc/haproxy/lua/services.lua
Using Lua services has the following benefits:
* The http status code in the log will always be correct - 413, 421, 495, 496, and the self-made 404 was being logged as 400.
* A Lua service can be issued from the backend, which will simplify the frontend config (future refactor).
* Configure the whole response within a service already being used - CORS Preflight.
=> Add 4xx error pages and CORS Preflight as Lua services

pkg/acme/signer.go, pkg/haproxy/instance.go
An acme account might be empty if endpoint or emails wasn't filled or the terms wasn't agreed. In this case the client shouldn't try to connect the acme environment and acme processing should be stopped.
=> check acme account before retrieving

pkg/converters/ingress/annotations/global.go, pkg/converters/ingress/annotations/host.go, pkg/converters/ingress/annotations/updater.go, pkg/converters/ingress/ingress.go, pkg/haproxy/config.go, pkg/haproxy/instance.go, pkg/haproxy/types/global.go, pkg/haproxy/types/global_test.go, pkg/haproxy/types/types.go
There is a couple of acme config that reflect in the haproxy configuration, eg enabled and socket. This change creates a distinct data type and field with acme-exclusive data and acme config used by haproxy. If only acmeData changes, a reload isn't needed.
=> improve equality comparison with acme changes

docs/content/en/docs/configuration/keys.md, pkg/common/ingress/controller/launch.go, pkg/converters/ingress/annotations/updater.go, pkg/converters/ingress/types/global.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/types.go, rootfs/Dockerfile, rootfs/etc/haproxy/template/haproxy.tmpl
Add options to:
* Change the process UID to 1001 / username `haproxy`
* Performs a chroot() in an empty and non writable directory
Other notable changes:
* Change the permissions in the file system to allow start the container as UID 1001
* Change the permission of the admin stats socket to `600`
=> Add security options

docs/content/en/docs/configuration/keys.md, pkg/converters/ingress/defaults.go
Listen a TCP port by default can lead to conflict when the controller runs in the host network - `9100` is already used by node exporter. Better tp enable if the exporter is needed than change or remove due to a conflict, which will refuse haproxy to start.
=> Defaults to not create prometheus listener

docs/content/en/docs/configuration/command-line.md, pkg/common/ingress/controller/controller.go, pkg/common/ingress/controller/launch.go, pkg/controller/cache.go, pkg/controller/controller.go, pkg/controller/metrics.go, pkg/converters/configmap/tcpservices.go, pkg/converters/helper_test/cachemock.go, pkg/converters/ingress/ingress.go, pkg/converters/ingress/ingress_test.go, pkg/converters/ingress/types/options.go, pkg/converters/types/interfaces.go, pkg/haproxy/dynupdate.go, pkg/haproxy/dynupdate_test.go, pkg/haproxy/instance.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/types.go, pkg/haproxy/utils/utils.go, pkg/types/helper_test/metricsmock.go, pkg/types/metrics.go, pkg/utils/timer.go
Add a starting version of a metric collector and exporter
=> Metric collector and exporter

examples/deployment/README.md
Fix deployment of TLS enabled haproxy, requiring a secret to be created in the same namespace as the ingress-controller
=> Fix TLS deployment

README.md, docs/content/en/docs/configuration/_index.md, docs/content/en/docs/configuration/command-line.md, docs/content/en/docs/configuration/keys.md, docs/content/en/docs/configuration/template.md, docs/content/en/docs/examples/modsecurity.md, examples/custom-configuration/README.md, examples/deployment/README.md, examples/dns-service-discovery/README.md, examples/modsecurity/README.md, pkg/common/ingress/store/main.go
* As in the official Kubernetes documentation it is called `ConfigMap` and not `configmap`
* https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/
=> [DOCS] Rename configmap to ConfigMap

docs/content/en/docs/configuration/keys.md, pkg/acme/server.go, pkg/haproxy/instance_test.go, rootfs/etc/haproxy/template/haproxy.tmpl
The internal ACME server (answer ACME challenges) and the http frontend (only if internal fronting TCP proxy is needed) uses unix sockets to the haproxy process communicate with. If the controller starts as root but `use-haproxy-user` is declared, haproxy wouldn't have permission to write to the socket. Now all sockets has `haproxy` as owner and `0600` as its permission, even if the process continue to run as root.
=> Change unix sockets user to haproxy

pkg/common/ingress/controller/controller.go, pkg/controller/cache.go, pkg/controller/controller.go, pkg/controller/metrics.go, pkg/converters/helper_test/cachemock.go, pkg/converters/ingress/ingress.go, pkg/converters/ingress/ingress_test.go, pkg/converters/types/interfaces.go, pkg/haproxy/instance.go, pkg/haproxy/types/types.go, pkg/types/helper_test/metricsmock.go, pkg/types/metrics.go
More than one domain could share the same certificate. The CN label is a good candidate to be used as the aggregation field
Old `hostname` label was changed to `domain` to avoid conflict.
=> Add CN label in the cert_expire metric

pkg/haproxy/config.go
HAProxy Ingress compares old and cur configuration objects to detect if an apiserver notification is in fact a configuration change. This will only work properly if slices are always in the same order. TCP services were being sorted only by name, which will lead to random restarts if only the port number changes. This happens because the source of the data is a `configmap.data[]` which is a map.
Fixes #493
=> Sort tcp services by name and port

docs/content/en/docs/configuration/keys.md, pkg/converters/ingress/annotations/updater.go, pkg/converters/ingress/types/global.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/types.go, rootfs/etc/haproxy/template/haproxy.tmpl
A global configuration used to override default scheme redirect.
This cannot be done as annotation in the current version because redirect code does not support `%[var()]`. In a future version, maybe v0.11, some frontend stuff will be moved to haproxy's backends so this config can be revisited and improved.
=> Add ssl-redirect-code global config key

docs/content/en/docs/configuration/keys.md, pkg/converters/ingress/annotations/backend.go, pkg/converters/ingress/types/annotations.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/types.go, rootfs/etc/haproxy/template/haproxy.tmpl
Adds the ability to convert the sha1 hash of the x509 certificate fingerprint, presented in hexadecimal, to lowercase digits. The default is to use uppercase digits.
=> Add ssl-fingerprint-lower config key

pkg/haproxy/instance.go
An output filter was added since `session-cookie-shared` config key due to a misplaced haproxy warning. This was already fixed and new releases were issued on all supported haproxy versions, so no need to filter anymore.
Should be applied up to v0.8.
=> Remove haproxy warning filter

pkg/haproxy/config.go, pkg/haproxy/config_test.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/frontend.go, pkg/haproxy/types/frontend_test.go, rootfs/etc/haproxy/template/haproxy.tmpl
Fixes a wrong assumption that a frontend need at least one ingress to be configured. Instead, a frontend should always be configured and issue a 404 page, since any host could be matched.
This also fixes configurations whose ingress objects have empty host - empty or wildcard `*` hosts are used to configure or overwrite the default backend without create a proper host entry, and were falling back in the same problem of not create the frontend.
=> Create frontends even without ingress

docs/content/en/docs/configuration/keys.md, pkg/common/ingress/controller/controller.go, pkg/common/net/ssl/ssl.go, pkg/controller/controller.go, pkg/converters/ingress/annotations/host.go, pkg/converters/ingress/annotations/host_test.go, pkg/converters/ingress/annotations/updater.go, pkg/converters/ingress/annotations/updater_test.go, pkg/converters/ingress/defaults.go, pkg/converters/ingress/types/annotations.go, pkg/converters/ingress/types/options.go
`auth-tls-strict` allows to build a strict configuration if an invalid auth-tls configuration is provided, either due to misconfiguration or due to asynchronous events that's going to happen and will fix the temporarily broken config.
The strict config is made using a self-generated certificate authority in the `ca-file` option, which will lead to two desired effects:
1. A certificate, if provided by the client, will be identified by the server. HAProxy doesn't allow to configure `verify optional` without a `ca-file`. If this option wasn't used, we couldn't distinguish between a request with or without a certificate on configs whose crt is optional
2. The request will always be denied due to invalid certificate authority (when verify-client is `on`) or when a client certificate is used …
=> Add auth-tls-strict configuration key

pkg/haproxy/instance_test.go, rootfs/etc/haproxy/template/haproxy.tmpl
A secure h2 connection to the backend was broken due to the missing `alpn` keyword. The protocol was correctly configured as `h2` but the TLS handshake was using the default alpn config which is `http1.1`.
=> Fix TLS handshake on backend

docs/content/en/docs/configuration/command-line.md, pkg/common/ingress/controller/controller.go, pkg/common/ingress/controller/launch.go
Provide the flag to ignore ingresses without a specified class.
Fixes #522
=> ignore ingresses without specified class

pkg/haproxy/instance.go
Ensures that the x509 certificate expiring metric is updated if a new certificate is issued.
=> Update crt metric if date changes

pkg/controller/controller.go, pkg/utils/queue.go, pkg/utils/queue_test.go
A work queue used to process certificate sign should be cleared when leaving the leader. Since k8s' work queue cannot be cleared or stopped, the work queue facade implemented a remove+recreate work queue reusing the same `Run()` event loop.
=> Clear acme work queue on stopped leading

pkg/controller/controller.go, pkg/controller/leaderelection.go, pkg/types/leaderelector.go
Leader elector stops when the leader cannot update the leading status. This change adds the leader elector bootstrap into a loop so it will restart the acquiring process.
=> restart the leader elector when stop leading

pkg/utils/queue.go, pkg/utils/queue_test.go
A concurrent read (`q.Run()`) and write (`q.Remove()`) to the `q.forget` map can panic and crash the controller. The writing was behind a mutex since the `q.Clear()` implementation. Now reading is also behind the same mutex.
=> fix race on failure rate limit queue

pkg/acme/signer.go, pkg/acme/signer_test.go, pkg/controller/controller.go, pkg/controller/metrics.go, pkg/types/helper_test/metricsmock.go, pkg/types/metrics.go
Add a new metric that collect sign request attempt, the reason, the domain list and if it succeeded.
=> add cert signing metrics

pkg/controller/metrics.go
Change the wrongly named metric `controller_processing_time_seconds_count` to a proper name `controller_processing_count`.
=> fix processing count metric name

docs/content/en/docs/configuration/command-line.md, pkg/common/ingress/controller/controller.go, pkg/common/ingress/controller/launch.go, pkg/controller/controller.go, pkg/controller/metrics.go
A new command-line option `buckets-response-time` used to overwrite the buckets of the histogram `haproxyingress_haproxy_response_time_seconds`. Such histogram is used to compute the response time (seconds) of the haproxy's admin socket.
=> add buckets-response-time command-line option

pkg/acme/signer.go, pkg/controller/metrics.go, pkg/types/helper_test/metricsmock.go, pkg/types/metrics.go
Use a proper label naming:
* `missing`: a new cert was issued because the current one wasn't found or was invalid
* `expiring`: the current cert expiring date is below the configured threshold
* `outdated`: the current cert doesn't fit the current spec, eg missing a domain
=> fix label naming of cert signing metric

docs/content/en/docs/configuration/command-line.md, pkg/common/ingress/controller/launch.go, pkg/common/ingress/types.go, pkg/controller/controller.go, pkg/haproxy/instance.go
Added URI `POST /acme/check` which starts check for missing, expiring or outdated certificates controlled by acme client.
=> add external call to certificate check

rootfs/Dockerfile
This update also fixes the HPACK decoder used for H2 connections.
See also:
* https://www.mail-archive.com/haproxy@formilux.org/msg36876.html
* https://github.com/haproxy/haproxy/commit/5dfc5d5cd0d2128d77253ead3acf03a421ab5b88
* https://nvd.nist.gov/vuln/detail/CVE-2020-11100
=> update to haproxy 2.1.4

pkg/converters/ingress/annotations/backend.go, pkg/converters/ingress/annotations/backend_test.go, pkg/converters/ingress/ingress.go, pkg/converters/ingress/ingress_test.go, pkg/haproxy/config.go, pkg/haproxy/config_test.go, pkg/haproxy/instance.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/frontend.go, pkg/haproxy/types/frontend_test.go, pkg/haproxy/types/host.go, pkg/haproxy/types/types.go, rootfs/etc/haproxy/template/haproxy.tmpl
Frontend group was used to group all frontends, binds and their related map files into a single entity. The need of a list of frontends doesn't exist anymore, so all inner entities and funcs are being moved on behalf of simplicity and cohesion, which will simplify future improvements. Further details in the message of the commits. There are no functionality changes.
=> Remove frontend group

pkg/converters/ingress/annotations/backend.go, pkg/converters/ingress/ingress.go, pkg/converters/ingress/ingress_test.go, pkg/haproxy/config.go, pkg/haproxy/instance.go, pkg/haproxy/types/host.go, pkg/haproxy/types/types.go
The current implementation uses two data structures, a slice which saves the order and a map which saves the index. To be reviewed. A getter facade was also implemented in order to standardise access to the ordered data.
=> Add host lookup with hash table

pkg/haproxy/types/backends.go, pkg/haproxy/types/backends_test.go, pkg/haproxy/types/types.go
The current implementation uses two data structures, a slice which saves the order and a map which saves the index. To be reviewed. Same approach used on hosts.
=> Add backend lookup with hash table

pkg/haproxy/config.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/backend.go, pkg/haproxy/types/frontend.go, pkg/haproxy/types/types.go, rootfs/etc/haproxy/template/haproxy.tmpl
Some HTTP status code cannot be generated by haproxy, eg 413. Validations that needed to issue such codes should be implemented in the frontend, so a backend with a customised error code could be selected.
This limitation was removed since error-only backends were changed to Lua scripts. A Lua script allows to build the response payload, use any customised error code, and such codes are correctly assigned in log messages.
=> Move max body size to the backend

pkg/haproxy/config.go
I added the missing call functions if we don't have ssl redirect
=> Server-alias doesn't not work on http:80 => 0.7.2 to 0.8.3 #565

docs/content/en/docs/configuration/command-line.md, pkg/converters/configmap/tcpservices.go, pkg/converters/configmap/tcpservices_test.go
Add a check interval option to the colon delimited list of argument of the tcp-service configmap. Default value is `2s` if not declared.
=> Add check interval on tcp service

docs/content/en/docs/configuration/keys.md, pkg/converters/ingress/annotations/global.go, pkg/converters/ingress/defaults.go, pkg/converters/ingress/types/global.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/types.go, rootfs/etc/haproxy/template/haproxy.tmpl
`use-forwarded-proto` extends `fronting-proxy-port` allowing a https-only requests behavior, without analysing `X-Forwarded-Proto`, which is forwarded to the backend.
=> Add use-forwarded-proto config key

pkg/common/ingress/controller/launch.go
Command-line option `--watch-namespace` configures the controller to read and use ingress objects from a single namespace. This would require fewer permissions,however the launch process tries to read the specified namespace, and such reading requires cluster wide permission. The launch process was updated to read an ingress resource instead.
=> Fix permission using watch-namespace

CHANGELOG.md, examples/PREREQUISITES.md, examples/auth/oauth/README.md
I've went through all documentation in all `.md` files and fixed some typos
=> docs: fixed typos

pkg/controller/controller.go, pkg/controller/listers.go
Some ingress annotations and command-line options can read resources from other namespaces. The watch-namespace command-line option just filter ingress resources from the informed namespace but all other resources are still read from the whole cluster. The force-namespace-isolation command-line option will enforce the read of just a single namespace, so the admin can configure a more strict permission to the controller's service account.
During lister refactor this behavior wasn't properly rewritten and watch namespace wasn't filtering ingress resources from a single namespace. This change fixes this behavior.
=> Fix watch-namespace option

docs/content/en/docs/configuration/command-line.md, go.mod, pkg/converters/configmap/tcpservices.go, pkg/converters/configmap/tcpservices_test.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/types.go, rootfs/etc/haproxy/template/haproxy.tmpl
Hello again @jcmoraisjr ,
I would like to propose a tentative implementation of ssl client verification for tcp services.
Currently we have a second instance of HAProxy whose sole job is to do ssl-offload AND verifying the client, ensuring the certificate presented by the client is indeed signed by the provided CA.
If we can do that ssl verification of the client directly at the ingress controller level, it would simplify things for us 😄 .
Let me know what you think !
=> TCP Services : SSL : Optionally Verify Client

docs/content/en/docs/configuration/command-line.md, docs/content/en/docs/examples/blue-green.md, docs/content/en/docs/examples/metrics.md, docs/content/en/docs/examples/metrics/whoami-ingress.yaml, docs/content/en/docs/examples/modsecurity.md, docs/content/en/docs/getting-started/_index.md, docs/haproxy-ingress.yaml, docs/static/resources/haproxy-ingress.yaml, examples/auth/oauth/README.md, examples/auth/oauth/app.yaml, examples/blue-green/README.md, examples/deployment/README.md, examples/deployment/haproxy-ingress.yaml, examples/modsecurity/README.md, examples/multi-tls/ingress-multi-tls.yaml, examples/rbac/ingress-controller-rbac.yml, examples/tls-termination/ingress-tls-default.yaml, examples/tls-termination/ingress-tls-foobar.yaml, pkg/common/ingress/controller/controller.go, pkg/common/ingress/controller/launch.go, pkg/common/ingress/controller/status.go, pkg/common/ingress/types.go, pkg/controller/controller.go, pkg/controller/listers.go, pkg/converters/ingress/ingress.go, pkg/converters/ingress/ingress_test.go
Signed-off-by: Ricardo Pchevuzinske Katz <ricardo.katz@gmail.com>
This PR intends to start using the newer Ingress APIs instead of the deprecated ones. 
Instead of using extensions/v1beta1 it will use the newer networking.k8s.io/v1beta1
Right now I'm changing only the docs, there's a need of decision whether the older API will still be supported (as Ingress NGINX) or be fully deprecated in further versions.
Creating a Ingress resource with networking.k8s.io works fine in the current API and Ingress Controller (tested with v1.17.0) and the extensions/v1beta1 will be fully removed from Kubernetes API in version v1.22
=> Update deprecated APIs in Docs

docs/content/en/docs/configuration/command-line.md, pkg/common/ingress/controller/controller.go, pkg/common/ingress/controller/launch.go, pkg/controller/controller.go, pkg/haproxy/config.go, pkg/haproxy/config_test.go, pkg/haproxy/dynupdate_test.go, pkg/haproxy/instance.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/backends.go, pkg/haproxy/types/backends_test.go, pkg/haproxy/types/global_test.go, pkg/haproxy/types/types.go, rootfs/etc/haproxy/template/haproxy.tmpl
Big clusters waste some time and cpu executing the haproxy template every time a configuration changes, even if such configuration is dinamically applied, leaving memory and disk configurations in sync. Most of the time is spent rebuilding all the referenced services, which is converted to haproxy backends.
Splitting the backends into smaller shards give haproxy ingress the ability to only update files that have changes to be applied, reducing io and cpu usage. The shard of a backend is chosen from the hash of its ID, so the same backend will always stay in the same shard provided that the number of shards isn't changed. Updating the number of shards will rebalance the backends.
=> add backend-shards command-line option

pkg/controller/cache.go
A list of changed objects is updated by Notify(), which listen events from informers. On every ingress parsing, this list is processed and cleared, waiting to be populated again on new events. The list of changed services wasn't being cleared, which means that every time any service was created or updated, the same hosts and backends tracked by that service was being synchronised and rewritten to disk every time any watched k8s object changes. Such "leak" would invalidate all the gains of partial parsing and backend-shards on a long running controller.
=> fix cleaning cache of changed objects

docs/content/en/docs/configuration/command-line.md, docs/content/en/docs/configuration/keys.md, pkg/common/ingress/controller/controller.go, pkg/common/ingress/controller/launch.go, pkg/controller/cache.go, pkg/controller/controller.go, pkg/controller/listers.go, pkg/converters/ingress/ingress.go
Pod listing and watching can be an expensive feature on big and noisy clusters. Listing and syncing pods in memory uses memory and watching them gives another reason to trigger the ingress parser.
Currently pod list is used in two features - blue/green and drain-support, and pod watch is only used by drain-support. Drain-support mode need pod list enabled and won't work if it's disabled. Blue/green on the other hand only uses pod listing to avoid bother k8s. If pod list is disabled, blue/green will query pod labels straight to k8s.
=> add disable-pod-list command-line option

pkg/haproxy/config.go
HAProxy maps building is a somewhat expensive operation that only need to be performed if there are pending changes on hosts or backends, because they don't change the model state, instead they just read the current state and update maps accordingly.
=> optimize haproxy maps building

pkg/haproxy/config.go, pkg/haproxy/instance.go, pkg/haproxy/types/backends.go, pkg/haproxy/types/backends_test.go, pkg/haproxy/types/host.go, pkg/haproxy/types/host_test.go
Partial ingress parse does its job tracking hosts and backends that could be impacted by a k8s update. However most of these hosts and backends may have been recreated without a single change, making conditional hosts map rebuild and backend shards configuration less optimized. Shrink consists of compare old and new state, removing hosts and backends without any change from the change tracking just before start resyncing model to disk.
=> shrink list of changed hosts and backends

docs/content/en/docs/configuration/keys.md, pkg/converters/ingress/annotations/backend.go, pkg/converters/ingress/annotations/global.go, pkg/converters/ingress/annotations/host.go, pkg/converters/ingress/annotations/host_test.go, pkg/converters/ingress/annotations/updater.go, pkg/converters/ingress/defaults.go, pkg/converters/ingress/types/annotations.go, pkg/converters/ingress/types/global.go, pkg/haproxy/config.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/types.go, rootfs/etc/haproxy/template/haproxy.tmpl
This is a second PR to close #573. I'm not entirely happy with the documentation of ssl-options, but this is the best I could come up with for now. Also I think it would make sense to deprecate/remove the no-tls* and force-tls* options in favor of ssl-min-ver and ssl-max-ver.
=> Host scope tls-alpn and ssl-options

pkg/common/ingress/controller/listers.go
Service changes wasn't starting config parsing due to the missing of a proper event handler. Annotations was being properly read if any other event starts the parsing.
=> Add service event handler

pkg/controller/controller.go, pkg/converters/ingress/ingress.go, pkg/converters/ingress/ingress_test.go, pkg/converters/ingress/types/options.go, pkg/haproxy/config.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/types.go
Default certificate was being configured during controller startup, which creates a read-only and never-change state. This configuration was moved to the ingress parsing phase, so every new sync will check if a missing secret was created or the secret was changed.
=> Configure default crt on ingress parsing phase

pkg/haproxy/config.go
Backend maps don't share state with other backends, so only added/changed backends need to be rebuilt.
=> Partial build of backend maps

pkg/converters/ingress/ingress.go, pkg/converters/ingress/ingress_test.go, pkg/converters/ingress/tracker/tracker.go, pkg/converters/ingress/tracker/tracker_test.go, pkg/converters/types/interfaces.go
Ingress is the starting point of all object parsing and tracking. This model works well on object changing, adding a missing backend or secret, but once everything starts from ingress objects, AddIngress event wasn't being properly tracked. This commit adds existent hosts and backends as tracked by the new ingress, given the chance to be removed and reincluded during the partial parsing.
=> Add hostname and backend tracking on addIngress

pkg/haproxy/types/backends.go
Changed backends behaves as old and new backends with the same name. The list of changed backends can be smaller removing old/new backend pair without changes.
The backend match wasn't taking care of `PathsMap` attribute which is changed and documented in the `config.WriteBackendMaps()`, and runs between two consecutive backend shrink.
=> Improve backend shrinking

pkg/haproxy/config.go, pkg/haproxy/types/maps.go
Frontend maps building still reads the whole model to update the map files. This was wasting an impressive amount of time sorting the maps on every insert - btw thank you `go tool pprof`. This commit moves the sort from every insert to just before usage. Time to build maps on a 5k domains cluster reduced from about 5000ms to 50ms.
=> Improve time of frontend maps build

pkg/converters/ingress/ingress.go
`ing.spec.rules[].HTTP` is a pointer which wasn't being checked when tracking added ingress objects. This only panics on partial parsing and if a new ingress without HTTP rule is added.
=> Fix sigsegv tracking added ingress

docs/content/en/docs/configuration/keys.md, pkg/haproxy/instance_test.go, pkg/haproxy/types/maps.go, pkg/haproxy/types/maps_test.go
The ingress path validation doesn't allow paths that doesn't start with a slash, so regex paths couldn't match the start of the string. Regex now behaves just like the `begin` match - it has an implicit starting `ˆ` match and no trailing `$`.
=> Add implicit starting boundary char in regex path match

pkg/converters/ingress/ingress.go, pkg/converters/ingress/ingress_test.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/host.go, pkg/haproxy/types/types.go
Most of the tracking stuff was missing on Ingress.Spec.Backend, resulting in an inconsistent state and sometimes a broken config. Hosts.defaultHost pointer was also removed, now the default `*` host is part of the Hosts.items map and inherits all the Hosts' partial parsing implementation, eg RemoveAll, ItemsAdd and Shrink.
=> Fix tracking and partial parsing of spec.backend

pkg/haproxy/types/host.go
ssl-passthrough uses an internal counter of hosts that uses such configuration. This speeds up queries to build or update the final configuration. The counter wasn't being decreased when a host is removed or updated (which is remove+add again).
=> Fix ssl-passthrough counter

docs/content/en/docs/configuration/command-line.md, pkg/common/ingress/controller/controller.go, pkg/common/ingress/controller/launch.go, pkg/controller/cache.go, pkg/controller/controller.go
Add an option to configure the delay between the first event of a clean notification cache and start the reconciliation process. This option avoids to start two consecutive reconciliations due to a batch update.
=> Add wait-before-update command-line option

docs/content/en/docs/configuration/keys.md, pkg/converters/ingress/annotations/global.go, pkg/converters/ingress/annotations/global_test.go, pkg/converters/ingress/annotations/updater.go, pkg/converters/ingress/defaults.go, pkg/converters/ingress/types/global.go, pkg/haproxy/config.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/types.go
`path-type-order` creates a list of priority path types. First types has higher precedence to choose the correct path in the case distinct paths of distinct types overlaps.
=> Add path-type-order global config

pkg/haproxy/instance_test.go, rootfs/etc/templates/haproxy/haproxy.tmpl
`rewrite-target` rewrites the path of the request to another path provided in the annotation. The haproxy keyword used was `replace-uri`, and an URI by definition can have an optional scheme and domain. Change to `request-path` will leave the configuration compatible with the data being matched.
=> Fix rewrite target match

pkg/haproxy/config.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/backend.go, pkg/haproxy/types/types.go, rootfs/etc/templates/haproxy/haproxy.tmpl
Move `ssl-redirect` related configurations to the backend. There are no changes in behavior or functionality. The main benefits of this change are: 1) smaller and faster frontend, 2) configuration simpler and easier to understand and evolve, once that ssl-redirect is a backend configuration key.
There are two impacted functionalities: 1) fronting-proxy - if proto header (http/https) usage is disabled, a https redirect should never happen; 2) ssl-passthrough has its own `_redirect_https` backend to link http requests.
=> Convert ssl-redirect to the new per path config

pkg/haproxy/dynupdate.go
Since the Add External HAProxy implementation, `HAProxyCommand` send a response message for every command sent. Dyn update always send three commands (change ip/port, change state, change weight) and some of them doesn't have a response. This behavior wasn't adjusted in the dyn update implementation and some logged haproxy responses was empty.
=> Log socket response only if message is not empty

pkg/haproxy/types/backends.go
Old and new backends are compared whenever a direct or indirect related ingress, service or endpoint changes. This comparison improves CPU usage avoiding cfg bulding if configurations match, and haproxy reload if a dynamic update can be made.
A static comparison check if all but endpoints match. This comparison need to ignore internal controller attributes related with endpoint, otherwise any change eg to the endpoints order would count as a backend change, which is not right.
`pathConfig` was added in Per Path Backend Config and since then it was incorrectly firing some backend cfg parsings. This commit remove it from the comparison.
=> Improve old and new backend comparison

CHANGELOG.md, docs/content/en/docs/configuration/command-line.md, pkg/common/ingress/controller/launch.go, pkg/controller/controller.go, pkg/haproxy/dynupdate.go, pkg/haproxy/dynupdate_test.go, pkg/haproxy/instance.go, pkg/haproxy/types/backend.go, pkg/haproxy/types/backends.go
Implement some missing pieces in the `--sort-backends` command-line option. This breaks compatibility between v0.7 and v0.8. Versions v0.7 and older shuffle backend endpoints as a default behavior while v0.8 uses the k8s order if nor provided.
Doc also updated to the new behavior. v0.8 CHANGELOG updated as well.
This should be merged up to v0.8.
=> Implement sort-backends

docs/content/en/docs/configuration/command-line.md, pkg/common/ingress/controller/controller.go, pkg/common/ingress/controller/launch.go, pkg/controller/controller.go, pkg/haproxy/instance.go, pkg/haproxy/types/backend.go, pkg/haproxy/types/backends.go
Add a few more options on how to sort endpoints of a backend. Currently `--sort-backends` switches between the same k8s endpoints order and naming order - which only makes sense if `backend-server-naming` was changed.
`--sort-endpoints-by` also brings back the old behavior (v0.7 and older) of missing `--sort-backends`: `random` option will shuffle endpoints of all backends whenever a haproxy reload is fired.
=> Add --sort-endpoints-by command-line option

.github/workflows/closeissues.yaml
Signed-off-by: Ricardo Pchevuzinske Katz <ricardo.katz@gmail.com>
As proposed in #614 this GH Action can close stale issues. The parameters are configurable in the yaml.
This PR needs the creation of a label called "Stale" so the bot can mark stale issues after some inactive time.
=> Adds a GH Action to close stale issues

pkg/converters/ingress/ingress.go, pkg/converters/ingress/ingress_test.go, pkg/haproxy/dynupdate.go, pkg/haproxy/dynupdate_test.go, pkg/haproxy/types/backends.go
Since v0.11, all cluster updates try to be partially applied in the in-memory model. This is addressed building an object tracking, followed by purging the old state and recreating these same objects in the new state. In short ingress objects track hostnames, services and secrets, and services track endpoints.
Default backends wasn't being updated because it exposes a service without using an ingress object, so endpoints are deployed on a full synchronization, including de first one, and wasn't tracker anymore. This update creates a dummy tracking point to bind the default backend endpoints and the haproxy model.
This update also needed to manage an issue with the backend ID: the default backend is renamed to `_default_backend` when assigned as such, and changed back when unassiged. This …
=> Fix dynamic update of the default backend

pkg/converters/ingress/ingress.go, pkg/converters/ingress/ingress_test.go, pkg/haproxy/config.go, pkg/haproxy/dynupdate_test.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/backends.go, pkg/haproxy/types/types.go
The default backend configured via a command-line option has a special name since ages. This comes from a time when it was in fact a special entity created apart of the regular services referenced by ingress objects. Actually the default backend is also a regular backend that needs to be tracked and updated, and such special name is incompatible with future refactors planned in the backend entity. Iow the special name does not worth the effort anymore.
=> Configure default backend to not change backend ID

pkg/haproxy/instance_test.go, pkg/haproxy/template/funcmap.go, pkg/haproxy/types/backend.go, pkg/haproxy/types/backend_test.go, rootfs/etc/templates/haproxy/haproxy.tmpl
HAProxy limits the number of arguments and chars per configuration line, respectively in 64 and 2048. These limits can break the backend parsing in the following conditions: a big number of distinct paths or hostnames sharing the same backend, most of them has at least one per-path customized configuration, at least one of them has a distinct configuration.
This commit splits a long chain of matching hostname+path references into at most 30 items, and new lines of the same keyword are added until all paths have been matched.
Need to be merged up to v0.10.
=> Fix line too long on backend parsing

pkg/converters/ingress/annotations/backend.go
Basic auth users and passwords are stored in secret resources. We're properly tracking secret->userlist in the event of a secret update, and backends are also tracked but only when a new userlist is created.
A proper partial parsing need to track either a host or a backend from the haproxy model. If an untracked backend uses a tracked userlist, changes to this userlist will remove it without recreate, which will lead to failures in the configuration parsing.
This update enforces that a backend is always tracked in the event of a secret update, ensuring that partial parsing works properly.
=> Fix basic auth backend tracking

pkg/acme/signer.go, pkg/acme/signer_test.go
As in topic, this pr allows acme signer to work with wildcard dns in cert.
Instead of https://github.com/jcmoraisjr/haproxy-ingress/pull/693
=> Allow signer to work with wildcard dns certs

pkg/acme/signer.go, pkg/acme/signer_test.go, pkg/controller/cache.go
A certificate validation need to parse a x509 certificate in order to identify if it's still valid or if it need to be reissued.
Tasks:
=> Improve certificate validation of acme signer

docs/content/en/docs/configuration/keys.md, pkg/converters/ingress/annotations/updater.go, pkg/converters/ingress/types/global.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/types.go, rootfs/etc/templates/haproxy/haproxy.tmpl
A haproxy deployment, which is frequently reloaded due to configuration changes, might have a big number of old workers in memory if the workload has a number of long running connections, eg websocket. `worker-max-reloads` limits this number, terminating old workers that survived that number of reloads.
=> Add worker-max-reloads config option

docs/content/en/docs/configuration/command-line.md, docs/content/en/docs/configuration/keys.md, docs/content/en/docs/getting-started/_index.md, pkg/common/ingress/controller/controller.go, pkg/common/ingress/controller/launch.go, pkg/common/ingress/controller/status.go, pkg/controller/cache.go, pkg/controller/controller.go, pkg/controller/listers.go, pkg/converters/helper_test/cachemock.go, pkg/converters/ingress/ingress.go, pkg/converters/ingress/ingress_test.go, pkg/converters/ingress/tracker/tracker.go, pkg/converters/ingress/tracker/tracker_test.go, pkg/converters/types/interfaces.go
Follow the 1.18 ingress [spec](https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class) and implement `ingressClassName` support.
This doesn't remove `kubernetes.io/ingress.class` annotation support and its behavior, which continue to have precedence in the case of a conflict.
**Breaking backward compatibility**
Starting v0.12, HAProxy Ingress will ignore unclassified ingress resources. Deployments that does not declare `--ignore-ingress-without-class` should now declare `--watch-ingress-without-class`. This configuration can be ignored if all ingress resources of the cluster are classified: has either the `kubernetes.io/ingress.class` annotation or configures the `ingressClassName` field.
**Tasks**
=> Add ingress class support

docs/content/en/docs/configuration/keys.md
Path scope exists since ages but wasn't properly documented. This commit adds how it works and also changes to Path scope all the configuration keys that in fact are from this group.
Should be merged to all doc versions.
=> doc: add path scope

pkg/haproxy/config.go, pkg/haproxy/instance_test.go
Default or fallback certificate is defined in haproxy declaring it as the first certificate. It should be used in TLS handshakes when SNI is not provided or if the provided one does not have a match.
HAProxy Ingress uses `crt-list` to better implements Ingress spec: a valid certificate is not one that its CN or SAN has the provided SNI, but instead that one the user declares in the spec.tls hostname.
There is however a scenario which trigger the wrong path: if the default certificate is valid for a provided SNI, haproxy will use it in the handshake instead of a declared certificate - this happens because the default certificate, being the first one, is validated first.
This commit adds a `!*` in the snifilter of the default certificate. This will instruct haproxy to not add any of its …
=> Use default certificate only if provided SNI isn't found

pkg/converters/ingress/annotations/backend_test.go, pkg/haproxy/config.go
A basic auth's userlist can be reused if the same password secret is reused in more than one Ingress, or even on the same Ingress with two or more paths. The userlist was being duplicated due to a missing find func. This doesn't break the configuration because all the userlists have the same content and haproxy complains but doesn't refuse to start.
=> Fix duplication of userlist

docs/content/en/docs/configuration/keys.md, pkg/converters/ingress/annotations/backend.go, pkg/converters/ingress/types/annotations.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/types.go, rootfs/etc/templates/haproxy/haproxy.tmpl
Add a configuration key to enable `SameSite=<Lax|None>` on persistence cookie attribute. This is a syntax sugar to add `attr SameSite=None secure` in the `session-cookie-keywords` configuration key.
=> Add SameSite cookie attribute

pkg/controller/listers.go
ConfigMap now can be used as the IngressClass' Parameters target. Because of that ConfigMaps in the controller namespace are also being watched. However other ConfigMaps that changes periodically was starting the ingress parsing - eg the cm used for leader election which is update every few seconds.
This update checks if a ConfigMap's data attribute was changed, otherwise a reconciliation isn't started.
=> Only notifies ConfigMap updates if data changes

pkg/converters/ingress/ingress.go, pkg/converters/ingress/ingress_test.go
Since the very first controller version, the TLS spec was only configured if a corresponding hostname was found in the rules of the same ingress resource. This commit changes this behavior and reads the TLS array as an independent configuration.
Such update changes backward compatibility since a misconfigured TLS would be silently ignored. However the new behavior better implements the ingress spec.
=> Independently configure rules and TLS

docs/content/en/docs/configuration/keys.md, pkg/converters/ingress/annotations/backend.go, pkg/converters/ingress/annotations/backend_test.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/types.go, rootfs/etc/templates/haproxy/haproxy.tmpl
Configures OAuth2 from backend scope to path. This will allow to only configure OAuth2 in some paths of the same backend.
As of any backend -> path scope change, this should lead to backward compatibility change if the configuration has a previous conflict on its configuration.
Tasks:
=> Change oauth2 to path scope

rootfs/haproxy-reload.sh
The reload script uses the admin socket to read the current haproxy state, before reloading a new configuration. This state reading would fail the reload if the socket exists but is refusing connection, eg if haproxy has died.
=> Fix reload failure if admin socket refuses connection

rootfs/Dockerfile
The upstream `haproxy` images now have haproxy user with a distinct UID. We're now removing and adding the user again in order to preserve our old `1001` UID. Since this is a breaking change, we'll postpone to use the same `99` UID to the next release.
=> Readd haproxy user in the docker image

pkg/controller/metrics.go, pkg/haproxy/instance.go, pkg/haproxy/types/host.go, pkg/haproxy/types/types.go, pkg/types/helper_test/metricsmock.go, pkg/types/metrics.go
A full syncing happens whenever a global configuration changes, the default crt is updated or, if for any reason the lister event sends invalid data or it cannot be successfully processed. Whenever this happens, domains that was removed in the mean time continue to populate the crt expire gauge.
This commit rebuilds the gauge if the haproxy config need to be rebuilt. Note that, although such clean ups shouldn't be very often, when they happen the gauge will have incomplete data during a very small amount of time.
=> Clear the crt expire gauge when full sync

pkg/controller/controller.go, pkg/haproxy/instance.go
The very first config conciliation might happen before haproxy is properly running and listening to its master socket. This can happen if eg the haproxy image should be download and the controller image is present. The first conciliation will now wait until the admin socket can successfully answer `show info`, and will only exit to the loop after send a command without error or if the controller receives a sigterm.
=> Fix first conciliation if external haproxy is not running

docs/content/en/docs/examples/metrics.md, docs/content/en/docs/examples/metrics/prometheus.yaml
Metrics doc depends on the controller pod selector to allow Prometheus find the controller. Controller labels was changed when upgrading to Helm deployment. This update changes also the label used in the Prometheus config.
=> docs/metrics: Fix prometheus config

pkg/haproxy/instance.go, rootfs/haproxy-reload.sh
Save the current state might be a bit expensive if the configuration is very large. This update makes the reload script read the current state only if the state would be used later.
=> Create state file only if load-server-state is enabled

pkg/haproxy/instance_test.go, rootfs/etc/templates/haproxy/haproxy.tmpl
Change from `regsub` converter to `field` to remove the port number from the `hdr(Host)`. Some clients add the port number in the header which would lead to false 404 errors. Changed to `field` because it's cheaper.
=> Use field converter to remove port from hdr host

docs/content/en/docs/configuration/keys.md, pkg/haproxy/config.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/maps.go, pkg/haproxy/types/maps_test.go, pkg/haproxy/types/types.go, rootfs/etc/templates/haproxy/haproxy.tmpl
All hostnames and path matches, used eg to select a backend, uses haproxy's map to increase performance on clusters with hundreds of distinct hostnames+paths. This however doesn't work very well if paths of distinct match types are used - there is one map converter per match type and the configuration was classifying paths only under the same map file.
This commit checks path overlap of distinct match types and creates new map files if a precedence should be enforced. The config file and map files lay out remain the same if there isn't overlap or if they happen under the same match type.
Should be merged down to v0.11 when path types was first implemented.
=> Fix path precedence of distinct match types

docs/content/en/docs/configuration/command-line.md, docs/content/en/docs/configuration/keys.md, docs/content/en/docs/examples/blue-green.md, docs/content/en/docs/examples/metrics.md, docs/content/en/docs/examples/metrics/whoami-ingress.yaml, docs/content/en/docs/examples/modsecurity.md, docs/content/en/docs/getting-started/_index.md, examples/auth/oauth/app.yaml, examples/blue-green/README.md, examples/deployment/README.md, examples/modsecurity/README.md, examples/multi-tls/ingress-multi-tls.yaml, examples/tls-termination/ingress-tls-default.yaml, examples/tls-termination/ingress-tls-foobar.yaml, pkg/common/ingress/controller/controller.go, pkg/common/ingress/controller/launch.go, pkg/common/ingress/controller/status.go, pkg/common/ingress/types.go, pkg/controller/cache.go, pkg/controller/controller.go, pkg/controller/listers.go, pkg/converters/helper_test/cachemock.go, pkg/converters/ingress/ingress.go, pkg/converters/ingress/ingress_test.go, pkg/converters/types/interfaces.go
This migration maps v1beta1 to v1 changes, without adding any new functionality:
- spec.backend to spec.defaultBackend
- backend.serviceName/Port to backend.service
- port (intOrStr) to port.name/number
Resource backend wasn't implemented.
=> Update to networking.k8s.io/v1 api

pkg/haproxy/types/maps.go, pkg/haproxy/types/maps_test.go
HAProxy Ingress since v0.11 implements path types other then `begin` (the one from v0.10 and olders) and some sort of `regex` (when a regex alias or a wildcard hostname is used) since v0.11. Now we have full `regex` (may be used in the path of ingress spec), `exact` and `prefix` - respectively str and dir from haproxy acl. This also fits ingress v1 spec.
Up to v0.11.1, overlapping paths were being wrongly routed depending on the path type they use. This happens because haproxy doesn't have a common list where all the path types can be matched, but instead distinct maps that does distinct matches. We were matching `exact` first, followed by `prefix`, then `begin` and so `regex`. The first map with a match wins. But this would lead to wrong routes if eg one have `/api` as prefix and …
=> Fix shrinking of prioritized paths

pkg/haproxy/instance_test.go, rootfs/etc/templates/haproxy/haproxy.tmpl
HAProxy Ingress validates client certificates using ACL in order to give a http response. The samples used were `ssl_c_ca_err` that returns >0 if there is a problem in the ca bundle (depth>0), and `ssl_c_err` that returns >0 if there is a problem in the certificate itself. However, there were observed outdated client certificates that doesn't trigger a failure in `ssl_c_err` but it does in `ssl_c_verify` which also check against the CA bundle and motivated this update.
=> Improve crt validation with ssl_c_verify

pkg/haproxy/instance.go, pkg/haproxy/utils/utils.go, pkg/haproxy/utils/utils_test.go
HAProxy responses has just a few bytes, usually saying that a backend server was successfully updated. A 1k buffer is just enough to handle such responses. Since the external process implementation, one of the responses has a list of all running procs, which will easily fill that buffer depending on the number of old workers alive. These updates:
* continue reading the buffer up to the last byte.
* validate the length of incoming response, leading to zeroes or empties if truncated - instead of crash
=> Read the whole input when the response fills the buffer

pkg/acme/server.go
An unix socket is used to answer acme challenges - it is create whenever --acme-server command-line is enabled. However it isn't removed if haproxy ingress is abruptly stopped, eg when a crash occurs. Since v0.12 an external volume is created if haproxy is running as a sidecar, leaving the unix socket file alive between restarts, causing a crashloop in the controller if the acme server is enabled. This update ensures that the unix socket file isn't present when the server is started
=> Remove unix socket before start acme server

pkg/converters/ingress/ingress.go
Weights can be used to distribute distinct load to distinct servers in the same backend. An initial value greater the default 1 (one) can be configured so agents that changes server weight can properly work and adjust the weight in lower granularity.
The initial weight configuration isn't properly working when declared in the ingress resource because its usage occurs before the value is actually read from the ingress annotation. It works however when declared in the service - service has priority and is read in the same block the backend is created and configured with initial weight and other defaults. Moving down the reading just before starting the endpoint configuration fixes this.
=> Fix initial weight configuration

pkg/haproxy/dynupdate.go, pkg/haproxy/dynupdate_test.go
Dynamic updates need to check the size of the endpoint list size. Up to now the backend server list cannot dynamically grow, even when using DNS updates. HAProxy Ingress has a list of empty slots to dynamically update endpoints, forcing a reload only when no new empty slots can be found.
Kubernetes' ep based updates always rebalance new endpoints with empty slots so its size is at least as big as the old one, but DNS based only do this if a reload is needed. This update rebalance the new list, so future DNS based dynamic updates can work without needing to reload haproxy.
=> Fix incorrect reload if endpoint list grows

docs/content/en/docs/configuration/command-line.md, docs/content/en/docs/configuration/keys.md, pkg/controller/cache.go, pkg/controller/cache_test.go
A backward compatible implementation to allow specify a protocol where only a secret name was being used. If, instead a secret name a `proto://content` is used, such content will be searched based on the protocol. If a protocol isn't provided, `secret` is used as default.
Actually only `file` protocol is implemented which expects an absolute path, but others like `cm/configmap`, `http/s` can also be implemented in the future.
Internal names wasn't changed and so the public interface - currently all namings reference "secret". Docs updated where the protocol can be used.
=> Add protocol to allow content sources other than secret

pkg/controller/metrics.go, pkg/haproxy/dynupdate.go, pkg/haproxy/dynupdate_test.go, pkg/haproxy/instance.go, pkg/types/helper_test/metricsmock.go, pkg/types/metrics.go
Evolve dynupdate to recognize changes to the frontend's TLS certificate and apply it using the runtime api. The update also happens even if was detected that a reload should also be performed, so the configuration will be as updated as possible if for any reason the reload fails.
This code updates the minimal HAProxy version to 2.2. HAProxy 2.1 also implements TLS cert update, but this version cannot update crt-lists with filters - which we use in the default certificate.
=> Add dynamic update of frontend's tls certificate

docs/content/en/docs/configuration/keys.md, pkg/converters/ingress/annotations/global.go, pkg/converters/ingress/types/global.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/types.go, rootfs/etc/templates/haproxy/haproxy.tmpl
The `custom-sections` global configuration key adds unindented configuration in the config file, giving the ability to create new HAProxy sections.
=> Add custom-sections global option

pkg/haproxy/instance_test.go, pkg/haproxy/types/frontend.go, rootfs/etc/haproxy/template/haproxy.tmpl
Some hostname+path matches happen in the backend to identify if a configuration should or should not be applied. Examples are whitelist, cors, hsts and rewrite path. Frontend matches are correctly using a regex if a wildcard hostname is used. Backends also work but only if all paths share the same configuration, in this case a path ACL is not used. However backends that have distinct path configurations were not properly configuring regex based ACLs - they were trying to match wildcard hostnames with -m begin.
This update adds to the backend the same hostname check used in the frontend, which converts begin match to a regex match if a wildcard hostname is used.
=> Fix backend matches if hostname uses wildcard

docs/content/en/docs/configuration/keys.md, pkg/converters/ingress/annotations/global.go, pkg/converters/ingress/annotations/global_test.go, pkg/converters/ingress/types/global.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/types.go, rootfs/etc/templates/haproxy/haproxy.tmpl
Allows to configure any internal proxy - listen, frontend or backend - using a single configuration key as a multi section value. Each section of the configuration adds custom snippet to distinct proxies.
=> Add custom-proxy configuration

pkg/haproxy/instance_test.go, pkg/haproxy/types/maps.go, pkg/haproxy/types/maps_test.go, rootfs/etc/templates/haproxy/haproxy.tmpl
Map keys are built using sysadmin/user defined hostnames and paths. We concatenate both when building the map file, and also concatenate hdr(host) and path from the incoming request. This works pretty well on beg and reg match types. Since v0.11 we have also dir (Prefix from ingress pathType) and str (Exact). The later also work well with this construction, but str (Prefix) does not behave as expected from the end user perspective.
Take this map example:
```
domain.local/ backend1
sub.domain.local/ backend2
```
and this request:
```
sub.domain.local/domain.local
```
A begin or regex match type would choose backend2, and this is the expected behavior for prefix as well, but due to how haproxy implements -m dir, backend1 would be chosen.
When using dir match type, haproxy slices the request …
=> Fix prefix path type if the path matches a domain

docs/content/en/docs/configuration/keys.md, pkg/converters/ingress/annotations/global.go, pkg/converters/ingress/types/global.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/types.go, rootfs/etc/templates/haproxy/haproxy.tmpl
Allows to customize configmap based TCP services with configuration snippets. All TCP services receives the same configuration.
=> Add custom-tcp configuration

docs/content/en/docs/configuration/keys.md, pkg/converters/ingress/annotations/host.go, pkg/converters/ingress/annotations/host_test.go, pkg/converters/ingress/annotations/updater.go, pkg/converters/ingress/defaults.go, pkg/converters/ingress/types/annotations.go, pkg/haproxy/config.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/host.go, pkg/haproxy/types/maps.go, pkg/haproxy/types/types.go, rootfs/etc/templates/haproxy/haproxy.tmpl
A server redirect allows to configure source domains that, if provided in a request, should redirect to the domain configured in the ingress' spec. Valid hostnames will always have precedence, which means that in the case of a match, the redirect will not happen.
As a host scoped config, two new maps were created (redirect source and status code) which will only be used if the functionality is also used.
=> Add server redirect options

pkg/converters/ingress/ingress_test.go, pkg/haproxy/instance_test.go, rootfs/etc/templates/haproxy/haproxy.tmpl
SSL passthrough domains are added in the same hostname maps used to route http requests. They share most of their configurations with a few exceptions. One of these exceptions weren't properly implemented - default host was always being configured in the http proxy. This update checks if the default host is an ssl passthrough, properly configuring it in the tcp proxy instead.
=> Fix default host if configured as ssl-passthrough

pkg/controller/cache.go, pkg/converters/ingress/ingress.go, pkg/converters/types/interfaces.go
`needFullSync` is a k8s cache status flagged when a changed resource cannot be properly identified. This status instructs HAProxy Ingress to parses all the ingress resources and build a new haproxy model from scratch, instead of try to perform a partial parsing.
The status was being read just after a cleanup, so a full sync wouldn't run if required. This update moves the current status to the changed objects struct just before being cleaned up.
=> Fix reading of needFullSync status

docs/content/en/docs/configuration/keys.md, pkg/converters/ingress/annotations/host.go, pkg/haproxy/config.go, pkg/haproxy/instance_test.go
A ssl-passthrough host cannot inspect uri and http headers because the request isn't offloaded in haproxy - a TCP tunnel is created instead. This however isn't true for the plain http side of the configuration, which up to now can only be configured with a 302 redirect (default behavior) or a plain http port in the same backend.
This update adds the ability to configure non root paths. Such paths does not change how the https side behaves, but do so for the http one. `ssl-passthrough-http-port` config key continue to be supported in the same way, but now act as a fallback - how the request will be handled in the http side if a path isn't found.
Hostnames configured as `ssl-passthrough` will now add non root `/` paths of these hostnames to the HAProxy's HTTP port. v0.12 and older …
=> Add non root path support on ssl-passthrough

pkg/converters/ingress/ingress.go, pkg/converters/ingress/ingress_test.go
Any distinct TCP service port can have it's own default certificate - a certificate that should be used when SNI doesn't match or isn't used at all. This differs from HTTP services because a default certificate is already configured via command-line and all HTTP ingress need to use the same configuration because the listening port is always the same (defaults to 443). Before this update, an empty `ingress.spec.tls[].hosts[]` list was ignoring the secret name on TCP services.
=> Allow default crt on tcp service

docs/content/en/docs/configuration/command-line.md, docs/content/en/docs/configuration/keys.md, docs/content/en/docs/examples/blue-green.md, docs/content/en/docs/examples/metrics/whoami-ingress.yaml, docs/content/en/docs/examples/modsecurity.md, pkg/common/ingress/controller/controller.go, pkg/common/ingress/controller/launch.go, pkg/converters/ingress/annotations/mapper.go, pkg/converters/ingress/annotations/mapper_test.go, pkg/converters/ingress/annotations/updater_test.go, pkg/converters/ingress/ingress.go, pkg/converters/ingress/ingress_test.go, pkg/converters/ingress/types/options.go
This update converts the annotations prefix to a slice, allowing to configure more than one supported prefix. Using a list of prefix makes it possible to conveniently change the default value without breaking backward compatibility. In the case of a conflict, the prefix that appears first in the command-line option will have precedence.
=> Allow to configure a list of annotations prefix

docs/content/en/docs/configuration/keys.md, pkg/converters/ingress/annotations/host.go, pkg/converters/ingress/annotations/host_test.go, pkg/converters/ingress/annotations/updater.go, pkg/converters/ingress/defaults.go, pkg/converters/ingress/ingress.go, pkg/converters/ingress/types/annotations.go, pkg/converters/ingress/types/global.go, pkg/haproxy/config.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/host.go, pkg/haproxy/types/types.go, rootfs/etc/templates/haproxy/haproxy.tmpl
This update adds some improvements to the just added redirect options. From now they are named redirect from and redirect to, which covers a few more use cases. Redirect code configurations were converted to global options due to the lack of dynamic config from HAProxy http-request redirect.
=> Add new redirect options

docs/content/en/docs/configuration/keys.md, pkg/converters/ingress/ingress.go, pkg/converters/ingress/types/annotations.go
Scopes are used to identify and log configuration conflict, and also to group configurations related to the same annotation mapping. Path type was wrongly configured as host scope and, although it was working as expected, a conflict warning was being logged if using two distinct path types in the same hostname. Change to path scope removes the warning without changing the behavior.
=> Fix path-type conflict warning

docs/content/en/docs/configuration/keys.md, pkg/converters/ingress/annotations/backend.go, pkg/converters/ingress/annotations/backend_test.go, pkg/converters/ingress/defaults.go
`auth-request.lua` sanitizes header names from the authentication service in a predictable way. So instead of document this to the user, we're now running the same sanitization in code, simplifying the user interface with the configuration key. Now `auth-headers` and `oauth-headers` can configure just the header name (the same name is copied from the auth service), another header name as the source, as well as a HAProxy variable name. The later gives some flexibility and preserve backward compatibility. Vars are identified from the prefix used in the name, and if identified, their names are used verbatim instead of performing the sanitization.
=> Accept header names in auth and oauth-headers

pkg/haproxy/config.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/backend.go, pkg/haproxy/types/host.go, pkg/haproxy/types/maps.go, pkg/haproxy/types/types.go, rootfs/etc/templates/haproxy/haproxy.tmpl
This update fixes two issues in rules with default host (empty hostname)
The first one is in the backend, the per path matching was trying to match the hostname with an internal representation. In this case only the path should be matched after the non empty hosts has been failed.
The other one is in the haproxy's frontend, the path was being matched with path_beg despite of the path type configuration. Now default host match uses a map just like non empty hosts.
=> Fix per path filter of default host rules

docs/content/en/docs/configuration/keys.md, pkg/converters/ingress/annotations/backend.go, pkg/converters/ingress/annotations/backend_test.go, pkg/converters/ingress/annotations/updater.go, pkg/converters/ingress/types/annotations.go, pkg/haproxy/dynupdate.go, pkg/haproxy/instance.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/backend.go, pkg/haproxy/types/backend_test.go, pkg/haproxy/types/backends.go, pkg/haproxy/types/types.go, rootfs/etc/templates/haproxy/haproxy.tmpl
A source address defines the address an outgoing connection will use to send the request to the backend server. Due to the 64k limit of ephemeral TCP ports per IP address, the maximum of concurrent connections cannot exceed 64k. `source-address-intf` allows the global or per ingress/service configuration of network interfaces used to list valid IPv4 from each host. Each IPv4 from the list is fairly distributed among all servers of all configured backends.
This is a static and per server configuration, each server/endpoint line receives its own outgoing source. Because of that, backends that use DNS resolver ignores this configuration since such backends uses server templates instead of static config.
=> Allow more than 64k outgoing conn with source addr

pkg/converters/ingress/annotations/backend.go, pkg/converters/ingress/annotations/backend_test.go
The domain validation on `secure-sni` and `secure-verify-hostname` config keys were missing a dash `-`, incorrectly issuing a valid `some-domain.tld` domain as invalid. This update also check if a dot is used and the tld is 2 <= size <= 6.
=> Fix domain validation on secure backend keys

docs/content/en/docs/configuration/command-line.md, pkg/common/ingress/controller/launch.go
Most of the API server warnings are related with API deprecation, and these logs are generated every now and then, flooding controller logs from clusters that have few syncs. This option adds the ability to disable these logs.
=> Add option to disable API server warnings

docs/content/en/docs/configuration/keys.md, pkg/converters/gateway/gateway.go, pkg/converters/ingress/annotations/backend.go, pkg/converters/ingress/annotations/updater.go, pkg/converters/ingress/annotations/updater_test.go, pkg/converters/ingress/defaults.go, pkg/converters/ingress/types/annotations.go, pkg/haproxy/config.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/backend.go, pkg/haproxy/types/host.go, pkg/haproxy/types/types.go
Since at least v0.8, controller adds domains in both HTTP and HTTPS maps despite the use of the `tls` attribute. This behavior goes against the Ingress spec but cannot be simply fixed due to backward compatibility. This config key adds the ability to configure HTTPS without the need of the `tls` attribute and can be globally changed. Its default value is
`true` to preserve the behavior of current and older versions.
Should be merged to v0.12.
v0.13 will merge this update changing the default value to `false`, which will impact deployments with Ingress resources that doesn't configure `tls` attribute. Such deployments by default will not configure HTTPS anymore. This configuration can be changed to `true` to bring back the v0.12 behavior, or `tls` attribute should be configured on every …
=> Add ssl-always-add-https config key

docs/content/en/docs/configuration/keys.md, pkg/converters/ingress/annotations/backend.go, pkg/converters/ingress/annotations/backend_test.go, rootfs/etc/lua/auth-request.lua
This update adds the ability to call the external authentication service using the same method provided by the user. Current option are only static and pre configured methods. The reading of the request method was delegated to the Lua script, because parameters to a Lua script cannot be interpolated.
=> Add option to copy client method to auth-url

docs/content/en/docs/configuration/keys.md, pkg/converters/ingress/annotations/backend.go, pkg/converters/ingress/annotations/backend_test.go, pkg/converters/ingress/annotations/validator.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/types.go, rootfs/etc/templates/haproxy/haproxy.tmpl
`cors-allow-origin` configuration key now allows a list of Origins. The `Access-Control-Allow-Origin` response header will be built based on the provided Origin, falling back to the first option if Origin cannot be found in the list.
=> Allow a list of origins in cors-allow-origin config

pkg/converters/ingress/ingress.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/types.go, rootfs/etc/templates/haproxy/haproxy.tmpl
A haproxy backend naming uses the service namespace and name, and also the port of the service. Kubernetes has a number of ways to reference a port, which can be a number or a name, and both can be of the service itself or the target (a pod). Current implementation just use the target reference, and being a number make it in sync with the port number in the target server. Anyway this is just a naming convention, except when DNS resolvers are in place.
The DNS resolver feature expects the name of the service port because this is the name the DNS knows. When port name and target port differs, the server-template is wrongly built with the target name. This commit adds a new `DNSPort` attribute that the DNS template should use to build the correct configuration.
=> Use the port name on DNS resolver template

pkg/controller/cache.go
Secrets with a CA bundle or crt+key pair uses the same internal struct to represent them. Distinct functions verify if the proper fields are filled to determine if the secret is correctly configured. The crt+key reading however is checking a common field used by CA and crt secrets, leading to a nil dereference when a certificate isn't properly configured. This update ensures that a certificate is properly configured. Thanks Maurilio for finding this.
Should be merged as far as v0.10.
=> Fix reading of tls secret without crt or key

pkg/converters/ingress/types/annotations.go
The annotation 'tcp-service-proxy-protool' was missing a 'c' in the word 'protocol'
=> Fix typo in 'tcp-service-proxy-protocol' annotation

pkg/haproxy/instance_test.go, rootfs/etc/templates/haproxy/haproxy.tmpl
HAProxy proxies use conditional configuration everywhere in order to HAProxy spend time only on tasks that has some value to the current configuration. Since the last default backend improvement (pr777), a new feature was added in the backend matching but some vars wasn't previously assigned. Such assignment is already under a big exception list, so it's currently more a rule than an exception. This update removes the conditional configuration on the https frontend, which fix workloads with only ingress without hostnames. Thanks Andrew for the fast report.
Should be merged up to v0.12 branch.
=> Fix backend match if no ingress use host match

pkg/common/ingress/controller/launch.go
Launch is actually copying the global configmap name from the command-line straight to the lister without checking its existence. The lister will watch configmap events and will only wake up if the name matches with the one provided in the command-line, so currently a mistyped name is silently ignored.
From now the configmap name is checked in the bootstrap process and will crash if not found or if the controller doesn't have permission to read it.
This should be merged as far as v0.10, but v0.12 and older should only log error instead, due to preserve backward compatibility with the current behavior.
=> Ensure that configured global ConfigMap exists

docs/content/en/docs/configuration/command-line.md
Hey, i don't know if this is correct or helpful, but i thought i'd try to go through the code and add all the command-line flags i can find.
I wasn't sure about the description on some of them, feel free to amend or tell me to do it better 😊
=> docs: Add all command-line options to list.

docs/content/en/docs/configuration/command-line.md, pkg/common/ingress/controller/controller.go, pkg/common/ingress/controller/launch.go, pkg/controller/cache.go, pkg/converters/helper_test/cachemock.go, pkg/converters/types/interfaces.go, pkg/converters/utils/services.go, pkg/converters/utils/services_test.go
`--disable-external-name` option refuses to configure services of type ExternalName, thus disallowing DNS lookups to configure the target address of backend servers.
=> Add disable-external-name commnand-line option

docs/content/en/docs/configuration/command-line.md, pkg/common/ingress/controller/controller.go, pkg/common/ingress/controller/launch.go, pkg/controller/controller.go, pkg/haproxy/instance.go
Creates a reload queue that manages how frequently HAProxy can be reloaded. This configuration allows a higher rate of dynamic updates with a low rate of HAProxy reloads. Two distinct queues controls dynamic updates and reloads, and a mutex ensures that these queues doesn't conflict with each other when reading and updating the in memory HAProxy model.
=> Add reload interval command-line option

pkg/converters/ingress/utils/utils.go, pkg/converters/ingress/utils/utils_test.go
`auth-url` accepts http/s or service protocol, and the later accepts namespaced service names, if the configuration allows, since `v0.13-snapshot.3`. Namespaced names has a slash just like URIs, so parsing the whole URL is somewhat tricky. A domain name without dots was being matched as a namespace and concatenated with the first dir of the path, leading to a lookup error. This update fixes this behavior and also adds a few more unit tests covering more URL formats.
=> Fix auth-url parsing if hostname misses a dot

pkg/converters/ingress/annotations/backend.go, pkg/converters/ingress/annotations/backend_test.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/types.go, rootfs/etc/templates/haproxy/haproxy.tmpl
The attempt to configure auth external or oauth means that the backend should be protected. However the current implementation is leaving the backend unprotected if a misconfiguration is found - which can be an external failure like a dns lookup. This update ensures that an attempt to protect a backend will in fact protect it, and misconfigurations or failures during the configuration parsing means an always-deny behavior.
=> Always deny requests of failed auth configurations

pkg/common/ingress/controller/controller.go, pkg/common/ingress/controller/launch.go, pkg/controller/controller.go, pkg/controller/listers.go
A couple of changes to the help output of command-line options and some minor refactors without functionality changes.
* Improve text alignment and the description of some options
* Move flag initialization from the controller initialization code to the launch
* Deprecate `--disable-node-list` which wasn't being used
=> Updates to the help output of command-line  options

docs/content/en/docs/configuration/command-line.md, pkg/common/ingress/controller/controller.go, pkg/common/ingress/controller/launch.go, pkg/controller/controller.go, pkg/converters/ingress/annotations/backend.go, pkg/converters/ingress/annotations/backend_test.go, pkg/converters/ingress/annotations/updater.go, pkg/converters/types/options.go
This option allows to disable annotation based configuration snippets, partially or completely. Configuration snippets can be the source of failures in the HAProxy reload, and also vulnerable configurations.
=> Add disable-config-keywords command-line options

docs/content/en/docs/configuration/keys.md, pkg/converters/ingress/annotations/global.go, pkg/converters/ingress/defaults.go, rootfs/etc/templates/haproxy/haproxy.tmpl
Removes the default value of 2 threads and let HAProxy configures threads automatically if the configuration is not provided. It's preferable more than less threads on a poorly configured system (or benchmark).
Compatibility notes: this might change the number of configured threads on deployments that doesn't configure an explicit value. The number should be updated to the number of CPUs available to the HAProxy process, or to one thread if the platform doesn't support CPU affinity.
=> Change nbthread to use all CPUs by default

pkg/haproxy/dynupdate.go, pkg/haproxy/dynupdate_test.go, pkg/haproxy/instance.go, pkg/haproxy/socket/socket.go, pkg/haproxy/socket/socket_test.go
Add option to change from the open/send/close sequence when communicating with client and master sockets to always leave the connection open, or reuse the same connection whenever more than one command should be sent. This improves the communication speed, and also makes the first step on behalf of retrieve data from stopping instances whose listening sockets aren't alive anymore.
=> Option to use client and master socket in keep alive mode

pkg/converters/gateway/gateway.go, pkg/converters/gateway/gateway_test.go
The change was required due to the Gateway API v1alpha1 requiring a non-empty string in `certificateRef.group`. With v1alpha2, `""` is now a valid value as per https://github.com/kubernetes-sigs/gateway-api/pull/562.
Fixes #830.
=> Gateway API: when using v1alpha1, certificateRef.group now accepts "core"

docs/content/en/docs/configuration/command-line.md, docs/content/en/docs/configuration/keys.md, pkg/common/ingress/controller/controller.go, pkg/common/ingress/controller/launch.go, pkg/controller/controller.go, pkg/converters/ingress/annotations/global.go, pkg/converters/ingress/annotations/global_test.go, pkg/converters/ingress/annotations/updater.go, pkg/converters/ingress/types/global.go, pkg/converters/types/options.go, pkg/haproxy/connections.go, pkg/haproxy/dynupdate.go, pkg/haproxy/dynupdate_test.go, pkg/haproxy/instance.go, pkg/haproxy/types/types.go, rootfs/etc/templates/haproxy/haproxy.tmpl
Active sessions of a stopping instance (`haproxy -sf -x`) are terminated just after `hard-stop-after` (our `timeout-stop`) times out and just before the old haproxy instance terminates. All the sessions at the same time. This option adds the ability to start the shutdown session at a configured time before the instance times out.
This is done on top of two new implementations: now sockets can be configured to leave the connection open, so we have a way to reach the stopping instance since its admin socket isn't being listened anymore (standalone/embedded only, we could reach an old instance using master/worker mode).
The other one is a new struct and associated funcs called connections, that holds the master socket (if used), admin sockets, a list of stopping instances, and also controls …
=> Add close-sessions-duration config key

pkg/haproxy/dynupdate.go, pkg/haproxy/dynupdate_test.go, pkg/haproxy/socket/socket.go, pkg/haproxy/socket/socket_test.go
haproxy recognizes the end of an instruction after a line break. This however doesn't work with set ssl cert due to the multi line payload, so two line breaks should be sent. set ssl cert was broken after the socket refactor since two consecutive commands - set ssl cert and commit ssl cert - are sent in the same connection. This update adds two line breaks after the first command, and also improves a manual test with set/commit ssl cert.
=> Fix set ssl cert end-of-command

pkg/haproxy/types/host.go
Since v0.13 certificates can be dynamically updated, however a reload was always scheduled due to an indirect reference from the backend to the frontend's certificate hash. This hash is used to the backend know if the frontend has a TLS certificate. When the certificate is changed, the hash is changed as well, leading to a configuration change that triggers a reload. The reference was moved to the filename, which can also be used to check TLS enabled and cannot be changed.
=> Fix dynamic update of frontend crt

pkg/haproxy/dynupdate.go, pkg/haproxy/types/backends.go
HAProxy backends can be sharded into smaller pieces, so unchanged backends don't need to be rebuilt, reducing the time spent regenerating the configuration file, specially on deployments with thousands of backends.
HAProxy Ingress controls the shards that should be rebuilt via the partial parsing implementation of ingress converter. Partial parsing tracks everything that need to be rebuilt, including backends. The internal HAProxy model controls the shards that should be rebuilt based on the backends tracked by the ingress converter. This means that changes made outside this controlled environment can be out of sync with configurations saved to disk, which is what HAProxy uses when it is restarted. This synchronization can be eventually fixed depending on new received events, sometimes …
=> Fix change notification of backend shard

docs/content/en/docs/examples/modsecurity.md, docs/static/resources/modsecurity-deployment-auditlog-sidecar.yaml, docs/static/resources/modsecurity-deployment.yaml
From our deployment/daemonset of ModSecurity, we have been noticing the ModSecurity pods hogging memory after our performance tests finish. There is no garbage collection done and the memory consumed only increases over time.
We believe this is due to documented memory leak issues with V2 of ModSecurity.
Our kubernetes native solution to this is to provide memory allocations to the deployment, to force restarts of the pods instead of hogging memory on nodes.
We've ran performance tests against this change to the deployment and there is no performance regression.
=> docs: add modsec resource limits to controls V2 memory consumption

pkg/converters/ingress/annotations/backend.go, pkg/converters/ingress/annotations/backend_test.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/types.go, rootfs/etc/templates/haproxy/haproxy.tmpl
An attempt to enable oauth should end up with a proper configuration, or the request should always fail in order to protect the backend service against misconfigurations. This change ensures that an attempt to configure oauth will lead to a proper configuration, or all requests will be denied.
This already works this way on v0.13, should be merged between v0.12 and v0.10.
=> Always deny requests if oauth is misconfigured

pkg/converters/ingress/ingress.go
Resource tracking is used to identify resources that should be parsed due to a configuration change. Resources directly or indirectly related with what was changed is removed and recreated to ensure that old behavior doesn't survive in the new state. A new ingress is already tracked to ensure that the referenced hosts and backends are removed, but this wasn't happening with existent ingress that reference a new backend that was already referenced elsewhere - such hosts and backends was being properly tracked for future updates, but would be missing some new configurations provided by the ingress that started to reference them.
=> Fix ingress update to an existing backend

pkg/converters/converters.go
Legacy ConfigMap based TCP services has its own endpoint list that doesn't track partial parsing. The entry point was changed when Gateway API was added, it was was incorrectly configured to only run when a full sync is needed, or when the ConfigMap was changed, leading to new state not being reflected in the configuration. This update ensures that ConfigMap based TCP services is always parsed when something changes in the cluster.
=> Fix endpoint update of configmap based tcp services

pkg/haproxy/instance_test.go, rootfs/etc/templates/haproxy/haproxy.tmpl
A misconfigured auth external generates a http-request deny keyword, which would lead to a configuration parsing error if only some paths of the backend weren't properly configured.
Should be merged to v0.13.
=> Fix config parsing on misconfigured auth external

pkg/common/net/ssl/ssl.go
An undocumented but inherited behavior from the so called ingress controller common code base allows to use a ca.crt key along with crt and key. However a crt validation was failing due to the missing intermediate crts in the validation. There is no behavioral change when using crt and key without a ca.
=> Fix validation if ca is used with crt and key

docs/haproxy-ingress.yaml, examples/rbac/ingress-controller-rbac.yml
Due to the deprecation of beta Ingress APIs, they should also been removed/modified in the way supported in Kubernetes v1.22+. Also, `ingressclasses` has been missing since some time haproxy-ingress started to integrate with them.
https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/
Thanks in advance!
=> docs: update api group of rbac config

pkg/controller/cache.go, pkg/converters/configmap/tcpservices.go, pkg/converters/converters.go, pkg/converters/gateway/gateway.go, pkg/converters/helper_test/cachemock.go, pkg/converters/ingress/annotations/backend.go, pkg/converters/ingress/annotations/global.go, pkg/converters/ingress/annotations/host.go, pkg/converters/ingress/annotations/mapper.go, pkg/converters/ingress/ingress.go, pkg/converters/ingress/ingress_test.go, pkg/converters/tracker/tracker.go, pkg/converters/tracker/tracker_test.go, pkg/converters/types/interfaces.go, pkg/haproxy/dynupdate_test.go, pkg/haproxy/types/backends.go, pkg/haproxy/types/backends_test.go, pkg/haproxy/types/frontend.go, pkg/haproxy/types/frontend_test.go
Tracker is used to link kubernetes resources and haproxy entities each other, allowing to list, remove and rebuild all objects related with a configuration change. This is the base of the partial parsing implementation.
The codebase used in v0.11 (starting implementation) up to v0.13 is a lot bigger than necessary, coupled with k8s and haproxy types , and also tricky to extend and test. This update changes the code base to an abstract implementation that can be expanded without the need to write more code, but instead just declaring a new type to every new k8s or haproxy type that need to be tracked.
Both old and new code base are compatible, they only change in the interface declaration, and the new one doesn't have a special behavior when the target doesn't exist - being missing or not, …
=> Refactor tracker to an abstract implementation

pkg/haproxy/socket/socket.go, pkg/haproxy/socket/socket_test.go
HAProxy's admin socket always respond in a fraction of a millisecond and should only take a bit more time if the proxy is 100% saturated, even so a response should be received within some hundreds of milliseconds. A fix 5s timeout is being added in the socket calls as a protection mechanism to the event loop that parses kubernetes resources - if for any reason, eg a controller bug, makes controller and HAProxy disagree who should be speaking, this timeout will make the controller give up instead of blocking the event loop forever.
=> Add read and write timeout to the unix socket

pkg/converters/ingress/annotations/backend.go, pkg/converters/ingress/annotations/backend_test.go
The mitigation of CVE-2021-25740 added a command-line option to allow a sysadmin to partially or completely remove backend configuration snippet. This option added a new code where there was only a straightforward assignment. This code fails on how to check if a configuration has a source and, instead of adjust the logging message, the whole assignment was being skipped. However a global configuration by definition doesn't have a source, leading to backend configuration snippet being skipped if not configured via ingress or service annotation.
This fix should be merged up to v0.10.
=> Fix global config-backend snippet config

docs/content/en/docs/configuration/command-line.md, pkg/common/ingress/controller/controller.go, pkg/common/ingress/controller/launch.go, pkg/controller/cache.go
When defined as true, `--controller-class-precedence` with give a precedence to controller class over kubernetes.io/ingress.class annotation. This will be especially useful while migrating from one approach to another having zero downtime in mind. It can be removed once the support of ingress annotation is fully disabled.
I am here referring to situation when both IngressClassName and ingress annotation are defined in Ingress which results in
```W0923 07:50:41.725353       7 cache.go:715] ingress prometheus/prometheus has conflicting ingress class configuration, using annotation reference (false)``` in haproxy ingress controller logs.
=> Add --ingress-class-precedence to allow IngressClass taking precedence over annotation

pkg/haproxy/instance_test.go, rootfs/etc/templates/haproxy/haproxy.tmpl
it overwrites another settings header vary from annotations. We should remember to set manually vary origin when we
have multiple origins.
=> remove setting vary origin header always when multiple origins are set

pkg/controller/cache.go
Acme functionality needs permission to create or update secrets when a new certificate is issued, and also to save the client's private key. This permission isn't added in the default configuration. The func that creates or updates the secret should return an error if anything went wrong, but the variable that has the error instance was being redeclared inside the if block, and was always returning nil even if an error (eg missing permission) occur.
The same is happening with ConfigMap, which is used to save the challenge token.
=> Fix error message on secret/cm update failure

docs/content/en/docs/configuration/keys.md, pkg/acme/client.go, pkg/acme/client_test.go, pkg/acme/signer.go, pkg/acme/signer_test.go, pkg/acme/x/acme/acme.go, pkg/acme/x/acme/acme_test.go, pkg/converters/ingress/ingress.go, pkg/converters/ingress/types/annotations.go, pkg/haproxy/instance.go, pkg/haproxy/types/global.go, pkg/haproxy/types/global_test.go, pkg/haproxy/types/types.go
Since the deprecation of DST X3 root CA, which used to sign Let's Encrypt root CA, a few issues raised and can be summarized as:
* If the topmost certificate of the provided chain is issued by `DST X3`, clients that has `DST X3` on their trusted CAs bundle, care about the expiration of their CAs, and a somewhat old openssl, will fail to trust in the Let's Encrypt chain even if they trust in the Let's Encrypt's `ISRG Root X1`. Clients should update openssl or remove `DST X3` from their trusted CAs. This is the default chain provided by Let's Encrypt;
* If the topmost certificate is issed by `ISRG Root X1`, which is Let's Encrypt's root CA, old clients will fail to trust Let's Encrypt certificate, mostly Android older than 7.1.1.
Let's Encrypt production API adds alternative chains that can …
=> add acme-preferred-chain config key

pkg/controller/controller.go, pkg/converters/ingress/annotations/backend.go, pkg/converters/ingress/annotations/backend_test.go
`--disable-config-keywords` command-line option allows to define a comma separated list of blacklisted keywords. If not declared, an empty string is used as an input to `Split()`. This empty string is however converted in an array of one element with an empty string, and such empty keyword matches with empty lines, denying configurations with empty lines. This update ignores empty entries when parsing the custom snippet, and also `TrimSpace()` all the options in order to properly match with the custom snippet tokenizer.
=> Add disableKeywords only if defined

pkg/haproxy/instance_test.go, rootfs/etc/templates/haproxy/haproxy.tmpl
Historically var() sample fetch used to return string so a match method was optional. Currently var() returns undefined, and since 2.5 the match method is mandatory. This helps to not make bogus configuration, when e.g. an int type is expected but it's in fact matched as string. See https://www.mail-archive.com/haproxy@formilux.org/msg41341.html
This update should be merged as far as v0.12, which is the first controller version that supports external haproxy.
=> Add match method on all var() sample fetch method

docs/content/en/docs/configuration/command-line.md, docs/content/en/docs/configuration/keys.md, pkg/common/ingress/controller/controller.go, pkg/common/ingress/controller/launch.go, pkg/controller/controller.go, pkg/converters/ingress/annotations/backend.go, pkg/converters/ingress/annotations/backend_test.go, pkg/converters/ingress/annotations/updater.go, pkg/converters/types/options.go, pkg/haproxy/instance.go, pkg/haproxy/instance_test.go, pkg/haproxy/socket/socket.go, pkg/haproxy/socket/socket_test.go, pkg/haproxy/types/global.go, pkg/haproxy/types/types.go, rootfs/etc/templates/haproxy/haproxy.tmpl
Add the ability to run the embedded haproxy in master-worker mode. Master-worker runs in the foreground, allowing to control the lifecycle of the process in a dedicated goroutine, within an event loop that will relaunch the process in the case of an unexpected crash.
Default behavior remains the same, so daemon mode will continue to be used if no configuration option is added, this should probably be changed in a future version.
=> Add master-worker mode on embedded haproxy

pkg/haproxy/instance_test.go, rootfs/etc/templates/haproxy/haproxy.tmpl
Annotation based TCP Services has the ability to choose a TCP backend based on the TLS SNI extension sent by the client. HAProxy however has two distinct samples fetches for read the SNI extension, one used in pure TCP connections and the help of the inspect-delay, another one used on requests decyphered by haproxy. This distinction wasn't being made by the controller.
Should be merged to v0.13.
=> Fix sni sample fetch on ssl decyphered tcp conns

docs/content/en/docs/faq/_index.md
I was unable to complete a Proof of Concept demonstration of haproxy-ingress (due to poor performance) until I increased backend-server-slots-increment for my active workloads
As soon as I made that change, the POC passed beautifully
Add this to the 'How to improve performance' section.
=> docs: include tuning of free backend slots in performance suggestions

docs/content/en/docs/configuration/keys.md, pkg/converters/helper_test/marshal.go, pkg/converters/ingress/annotations/host.go, pkg/converters/ingress/annotations/updater.go, pkg/converters/ingress/ingress.go, pkg/converters/ingress/ingress_test.go
Small refactor in the `buildHostAuthTLS()`, allowing to reuse the same function to populate TLS authentication to both HTTP and TCP frontends.
=> Add auth-tls configurations to tcp services

docs/content/en/docs/configuration/keys.md, pkg/converters/ingress/defaults.go
`auth-tls-scrict` is used to define whether a misconfigured TLS based authentication should always fail, i.e. defines if misconfigured should ignore the configuration or create a fake configuration to protect the backend.
Historically HAProxy Ingress alerts and discards wrong configuration but this could lead to a security issue on configurations that protect applications. Strict option was added in v0.8 as false to preserve backward compatibility, and finally changed its default to true to improve security.
=> Change auth-tls-scrict from false to true

docs/content/en/docs/configuration/command-line.md, docs/content/en/docs/configuration/gateway-api.md, pkg/common/ingress/controller/launch.go, pkg/controller/listers.go
Change default value of `--watch-gateway` command-line option to true, so try to listen to gateway API CRDs by default. This new implementation will skip registration of listers and informers if the crds are not installed in the server, contrary to v0.13 which would always try to register them.
There is a backward incompatibility, a v0.13 controller that doesn't declare the command-line option would ignore gateway api resources, while v0.14 would find and configure them by default.
=> Check by default if gateway api crds are installed

pkg/haproxy/socket/socket.go, pkg/haproxy/socket/socket_test.go
Creates a new `show proc` parser compatible with haproxy 2.2 to 2.5. Added in a safe way to allow merging as far as controller v0.12 - version 2.4 and below will continue to use the old parser, minimizing the risk of adding an unknown bug from the new one.
Should be merged as far as v0.12, which is the first version that implements external haproxy and parses `show proc` output.
=> Add haproxy 2.5 support for external haproxy

pkg/haproxy/config.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/maps.go, rootfs/etc/templates/haproxy/haproxy.tmpl
HAProxy's subdir match type is used to implement the `Prefix` pathType. This match type however doesn't implement exactly what is expected from the `Prefix` type if a single slash is used as the pattern - ingress expects that `/bar` would match, but it doesn't, matching only `/bar/` instead. This works well with declared hostnames because HAProxy Ingress builds the pattern concatenating hostname and path, but this doesn't happen with the default hostname where the path is configured alone.
This update adds a prefix in the default hostname patterns, just like it's already happening with declared hostnames, in order to them to behave in the same way.
=> Fix match of prefix pathtype if using default host

pkg/haproxy/instance_test.go, rootfs/etc/templates/haproxy/haproxy.tmpl
If the TCP port is bound as SSL-enabled, i.e. terminating the SSL connection, `req.ssl_hello_type` is not set and the inspection delay would block the request unnecessarily.
The solution is to only perform the inspection and add the delay if we're passing through the SSL connection and still want to route based on SNI. The delay can be optional in this case as the `ssl_fc_sni` value is immediately available at that point.
=> Only inspect SSL handshake for SNI routing for SSL passthrough, fixes #912

docs/content/en/docs/configuration/keys.md, pkg/converters/ingress/annotations/backend.go, pkg/converters/ingress/annotations/backend_test.go, pkg/converters/ingress/types/annotations.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/types.go, rootfs/etc/templates/haproxy/haproxy.tmpl
`ssl-fingerprint-sha2-bits` defines the number of bits of the SHA-2 fingerprint of the client certificate of a mTLS request. The header `X-SSL-Client-SHA2` is only added if the configuration is declared.
=> Add ssl-fingerprint-sha2-bits configuration key

pkg/haproxy/instance.go
HAProxy 2.5 and newer has a new lay out for the `show proc` command. The compatibility change was recently implemented in the controller. Besides the lay out, the way to identity if an instance was properly started was changed as well. This update fixes the reading of this information. This impacts only haproxy running as an external process, and only with haproxy 2.5 and newer.
This update should be merged as far as v0.12, where external haproxy was first implemented.
=> Fix reload failure detection on 2.5+

pkg/controller/cache.go, pkg/controller/listers.go
Delete event from informers might return `cache.DeletedFinalStateUnknown` instead of the actual object if the object is removed from the api while the watch is closed, e.g. during an outage. Informers that need to check the state of a removed object must check the type, otherwise a panic would be issued. This update implements a safe typecast on the delete event of all informers that were missing it.
=> Check type assertion on all informers

pkg/controller/controller.go
AcmeCheck() is an instance's method that can be triggered from three distinct goroutines. Although it doesn't change the model, it reads it and can lead to inconsistent data or even a race in the map of acme related data if called concurrently with a model update. This commit prevents that AcmeCheck() is called during instance's model updates.
=> Add lock before call acmeCheck()

rootfs/start.sh
External HAProxy starts with a bare minimum configuration, just to serve as a placeholder to the first real configuration. We need this first configuration so we have a process to be reloaded remotely. This needs to be a bare minimum / invalid because in that stage we don't have information enough to create a real configuration.
This starting configuration however might lead to a false positive ready state from the cluster perspective because of the /healthz endpoint implemented in the starting configuration. This endpoint is being removed from that stage, so the cluster can property mark the pod as not ready and remove from load balancers until the real configuration is in place.
=> Remove readiness endpoint from starting config

docs/content/en/docs/configuration/keys.md
If this format is not followed following error is thrown:
`
2022/08/01 08:50:43 unable to parse static config: error reading global ConfigMap 'haproxy-ingress': an empty namespace may not be set when a resource name is provided
`
that actually is thrown by k8.
I'm not sure if it is a common knowledge to always use namespace when specifying a configmap. Ignore this if that is the case.
If not, then i guess the format can also be enforced at the time of parsing `--configmap` arg?
=> Documents the expected format for --configmap key

builder/Dockerfile, rootfs/Dockerfile
Sometimes HAProxy Ingress is released a few weeks after the upstream haproxy container, or sometimes a new release is needed to fix a security vulnerability. Adding `apk upgrade` during the container building process guarantee that the most up to date dependencies, in the date of the controller release, will be used in the generated image.
This should be merged to all maintained versions.
=> Add apk upgrade on container building

go.mod, go.sum, pkg/common/ingress/controller/status.go, pkg/haproxy/template/funcmap.go
@jcmoraisjr some small migrations to a newer version of the dependency for masterminds/sprig as well as removing the archived pkg/errors package.
=> Migrate to new versions / off deprecated packages.

pkg/converters/ingress/ingress.go, pkg/converters/ingress/ingress_test.go, pkg/converters/utils/services.go
A backend server is configured with the port number declared in the
service. However, services of type ExternalName doesn't need to have
a port declared, and since the v0.8 refactor, HAProxy Ingress refuses
to configure backends for services without port.
This update checks if the service is of type ExternalName and if the
ingress referencing this service uses a numeric port number. If true,
the port number declared in the ingress will be used as the port to
connect to the backend.
=> Add support for service external name without port

docs/content/en/docs/configuration/keys.md, pkg/converters/ingress/annotations/backend.go, pkg/converters/ingress/defaults.go, pkg/converters/ingress/types/annotations.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/types.go, rootfs/etc/templates/haproxy/haproxy.tmpl
Full issue is described here: https://github.com/haproxy/spoa-modsecurity/issues/3
**Note: This is a breaking change from 0.14 to 0.15**
This PR changes the default behavior (that we copied from the upstream spoa-modsecurity docs) of allowing requests through if modsecurity errors out or times out. Now, only a valid response from modsecurity (`txn.modsec.code=0`) will allow requests through.
Users can go back to the old behavior by setting `waf-fail-closed: false` which would mean that e.g. a flood of requests could overload modsecurity-spoa and trigger timeouts, which would allow requests through without being scanned by modsecurity.
=> Make WAF errors fail closed by default. Add waf-fail-closed=false to override

docs/content/en/docs/configuration/keys.md, pkg/converters/ingress/annotations/backend.go, pkg/converters/ingress/defaults.go, pkg/converters/ingress/types/annotations.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/types.go, rootfs/etc/templates/haproxy/haproxy.tmpl
This reverts commit ff2953bdb6346e944a42e4fbd1e87ef727c8433d, reversing changes made to 316b7ed13d28d7f5836450ad93287712cf0acf47.
Fixes #962 
Long-term fix likely involves changes to how the upstream spoa-modsecurity sets the return code.
=> Revert "Merge pull request #954 from mac-chaffee/fail-closed"

pkg/haproxy/connections.go, pkg/haproxy/instance.go
This should make the [Load Server State](https://haproxy-ingress.github.io/docs/configuration/keys/#load-server-state) feature work for setups where external haproxy is used.
=> Enable Load Server State feature for external haproxy

pkg/common/ingress/controller/controller.go, pkg/common/ingress/controller/launch.go, pkg/common/ingress/controller/status.go, pkg/common/net/ssl/ssl.go, pkg/controller/controller.go, pkg/controller/logger.go, pkg/haproxy/template/funcmap.go
`klog.Fatal()` adds stack traces alongside the message and we don't need that. All the logs comes from a bootstrap validation error, so we just need the message and quit the process with code>0. Changing all the `klog.Fatal()` to `klog.Exit()` do that.
=> Change klog.Fatal to klog.Exit

docs/.gitignore, docs/content/en/docs/configuration/keys.md, docs/content/en/docs/examples/modsecurity.md, docs/static/resources/coraza-deployment.yaml, pkg/converters/ingress/annotations/global.go, pkg/converters/ingress/types/global.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/types.go, rootfs/etc/templates/haproxy/haproxy.tmpl, rootfs/etc/templates/modsecurity/modsecurity.tmpl
This PR adds a new config value, `modsecurity-use-coraza`, which changes the WAF/SPOE configuration to support https://github.com/corazawaf/coraza-spoa
Specifically, this config matches the "experimental" branch of coraza-spoa. Slight changes in the args may be required in the future as the API stabilizes, so we do not provide default args in the source code (only in the docs).
To use, just set these values in the helm chart:
```
controller:
image:
repository: <must use an image based on this branch>
tag: <must use an image based on this branch>
config:
modsecurity-use-coraza: "true"
modsecurity-endpoints: 127.0.0.1:12345
modsecurity-args: "app=hdr(host) id=unique-id src-ip=src src-port=src_port dst-ip=dst dst-port=dst_port method=method path=path query=query version=req.ver …
```
=> Coraza support

pkg/haproxy/instance_test.go, rootfs/etc/templates/haproxy/haproxy.tmpl
Acme validation happens on plain HTTP and should skip redirects, so that the acme service (e.g. Let's Encrypt) can properly validate the domain ownership. This wasn't properly happening with `redirect-from` and `redirect-to` keys, which makes the signer to fail. This update skips those redirects when acme is enabled and path matches the acme challenge.
=> Fix host redirects when acme is enabled

docs/content/en/docs/configuration/keys.md, pkg/converters/ingress/annotations/backend.go, pkg/converters/ingress/annotations/backend_test.go
By default `auth-headers-*` copy all provided headers to/from auth service, client or backend. A non documented `-` makes no header to be copied and an empty string breaks the configuration. Now an empty string is internally converted to a dash and this option is also documented.
=> Makes auth-headers not copying on empty string

pkg/haproxy/instance_test.go, pkg/haproxy/types/host.go, rootfs/etc/templates/haproxy/haproxy.tmpl
mTLS configuration was being enabled if TLSAuthList map has at least one entry. This premise was valid when all mTLS aware hostnames were added to that list, which doesn't happen anymore with optional_no_ca properly implemented. Now mTLS is enabled when a host declares a CA bundle.
=> Fix mTLS when all hosts are optional_no_ca

docs/content/en/docs/configuration/keys.md, pkg/converters/ingress/annotations/backend.go, pkg/converters/ingress/annotations/backend_test.go, pkg/converters/ingress/ingress.go
Auth External works by parsing the authentication service url and looking for a pre-configured backend. The pre-configuration part works by making a normalization in the k8s service port number, so different inputs for the same service will output the same backend. This might change the port name of the backend on named port configurations.
A proper fix is to make the backend creation accessible by the updater code, so we don't need to pre-initialize the backend in the ingress step, and don't need to guess the backend port name in the updater step. So, for now, we'll improve logging and documentation.
This should be merged as far as v0.13, which implements the first version of auth external.
=> Add warning if auth external svc isnt found

pkg/converters/ingress/ingress.go, pkg/converters/ingress/ingress_test.go
Backend scoped annotations apply just once per service resource, and have the most precedence. With this behavior in mind, service annotations were being applied along with the annotation mapper creation. This works nice with backend scoped annotations.
Path scoped, however, has the ability to apply distinct values to the same backend. When path scoped annotations are applied via a service resource, only the first path is being applied, along with annotation mapper creation. This update ensures that the service annotations are applied on every pathlink that points to it. This change will spread service annotations over all referenced pathlinks, however this doesn't end up with duplicated configurations because the config builder already deduplicates configurations on the same key, with …
=> Fix path scoped annotation on service resources

docs/.gitignore, docs/config.toml, docs/content/en/_index.html, docs/content/en/docs/contribution-guidelines/_index.md, docs/package.json
I noticed while working on the Coraza docs that my version of Hugo was too new to render the docs locally, specifically the change from `blackfriday` to `goldmark` as the markdown renderer on v0.60. I also updated the node deps too.
**NOTE:** @jcmoraisjr It looks like you build and publish the site locally. If so, you'll need to update your local hugo version and run `npm update` before publishing if this PR is merged.
Other changes:
* Gitignore'd the .hugo_build.lock file (which was added [in a later version of Hugo](https://gohugo.io/news/0.89.0-relnotes/))
* Changed the baseURL, it's apparently supposed to be the full URL where the site is hosted: https://gohugo.io/getting-started/configuration/#baseurl Without this change, I just get 404s locally.
* Allowed rendering raw HTML which is …
=> Update to hugo v0.110.0 and update node deps

docs/content/en/docs/configuration/keys.md, pkg/converters/ingress/annotations/backend.go, pkg/converters/ingress/annotations/backend_test.go, pkg/converters/ingress/annotations/host.go, pkg/converters/ingress/annotations/mapper.go, pkg/converters/ingress/annotations/updater.go, pkg/converters/ingress/defaults.go, pkg/converters/ingress/ingress.go, pkg/converters/ingress/types/annotations.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/host.go, pkg/haproxy/types/maps.go, pkg/haproxy/types/types.go, rootfs/etc/templates/haproxy/haproxy.tmpl
External authentication services has the ability to inject headers on the fly in the current request. Such header will be visible to the backend server in the case the authentication succeed, and to the caller/client in the case the authentication fails. This works that way since v0.13.
Starting on v0.15 HAProxy Ingress has the ability to route requests based on HTTP headers, along with the well known hostname+path supported since the very first version. However headers added or updated by the authentication service isn't visible to HAProxy Ingress routing rules, this happens because the authentication service is called from the backend declaration for performance reasons, but the routing rules must be configured in the frontend due to its logic: it needs to choose a backend based on …
=> Add optional frontend based external authentication call

pkg/controller/services/services.go, pkg/converters/types/options.go
Bypass the ingress status update when update-status flag is disabled. The ability to skip sstatus update wasn't implemented in the new controller.
=> Skip status update when update-status is false

builder/Dockerfile, docs/content/en/docs/configuration/keys.md, rootfs/Dockerfile
HAProxy used to need to start as root due to binding ports, which's not needed anymore on somewhat modern kernels and container runtime.
This change breaks backward compatibility and should be added to the breaking changes of the changelog.
=> Change controller container to non root user

.golangci.yml, docs/content/en/docs/configuration/command-line.md, pkg/common/ingress/controller/controller.go, pkg/common/ingress/controller/launch.go, pkg/controller/legacy/cache.go, pkg/controller/legacy/controller.go, pkg/controller/legacy/listers.go, pkg/controller/services/cache.go, pkg/converters/configmap/tcpservices.go, pkg/converters/configmap/tcpservices_test.go, pkg/converters/gateway/gateway.go, pkg/converters/gateway/gateway_test.go, pkg/converters/helper_test/cachemock.go, pkg/converters/helper_test/k8sobjects.go, pkg/converters/ingress/ingress.go, pkg/converters/ingress/ingress_test.go, pkg/converters/types/interfaces.go, pkg/converters/types/options.go, pkg/converters/utils/services.go, pkg/converters/utils/services_test.go
Adds support for endpoint slices api to fetch endpoints.
Corresponding clusterrole changes https://github.com/haproxy-ingress/charts/pull/66
=> Adds support for EndpointSlices API in master

pkg/controller/cache.go
Fix missing delete notifications on gw-v1alpha2 by adding the event in the object change tracking.
=> Fix gw-v1alpha2 delete notifications

docs/content/en/docs/configuration/keys.md, pkg/converters/ingress/annotations/updater.go, pkg/converters/ingress/defaults.go, pkg/converters/ingress/types/global.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/types.go, rootfs/etc/templates/haproxy/haproxy.tmpl
Acme challenge path is used to validate domains. This should have priority when compared with redirects. TLS redirect already have a global config key that adds `/.well-known/acme-challenge` by default. We need this same configuration for redirect-from/to family as well.
=> Skip acme-challenge path on to/from redirects

pkg/converters/converters.go
This update ensures that configmap based TCP services are applied in the very first controller reconciliation. Cur config is only defined from the second reconciliation, so the TCP service would be empty if the controller bootstrap doesn't call the reconciliation at least twice.
=> Fixes configmap based tcp sync

pkg/haproxy/types/tcpbackend.go
Dynamic update code relies on comparing tcp services structs in order to verify whether any tcp service has changed or not, and if so, haproxy need to be restarted. Endpoint list is the only tcp data that might lead to differences in the case the same values are present, but in distinct order. Because of that we're applying a sort in order to generate predictable, hence comparable results.
=> Ensure predictable tcp by sorting endpoints

docs/content/en/docs/examples/metrics.md, docs/content/en/docs/getting-started/_index.md
Apparently using ingressClassName has been preferred over annotations since k8s 1.18: https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation
This PR just updates the two examples we have in the docs to use ingressClassName instead of the annotations. Figure we ought to send new users down the right path!
=> Prefer ingressClassName over annotations in docs

pkg/converters/ingress/annotations/host.go, pkg/converters/ingress/annotations/host_test.go
Redirect-from configuration key defines the source hostnames that should redirect to the one configured in the ingress manifest. This is not properly working with ingress that adds more hostnames in the TLS section because haproxy ingress adds all those hostnames as regular ones. Adding as a regular hostname is needed in order to make haproxy choose the right certificate in the TLS handshake.
The following change is making redirect-from apply redirects only on hosts that have a backend association, which would be otherwise ending up in a 404 error anyway.
=> Redirect hosts only to domains with associated backends

pkg/converters/utils/services.go, pkg/converters/utils/services_test.go, pkg/haproxy/types/tcpbackend.go
Endpoints (internal haproxy ingress struct, not the k8s one) are part of the building blocks to configure a backend or a tcp listener. HAProxy Ingress uses deep equals on some structs in order to identify equality, hence the ability to skip a reload event. When two endpoint arrays have the same content but on distinct order, they are not considered equals, although it should from the haproxy and haproxy ingress perspective. Because of that we're sorting them.
The former update (which we're reverting here) was sorting the endpoints after they get named, so the order is right but some names might be changed. Now we're sorting the endpoints on its source.
=> Create endpoints on a predictable order

pkg/controller/reconciler/watchers.go
Endpoints resource doesn't implement generation, so generation based predicates doesn't work on it, making endpoints not to dispatch events. We already have a func based predicate in place, so we can just remove the generation based one altogether.
=> Remove generation predicate on endpoints

pkg/haproxy/config.go, pkg/haproxy/types/backends.go
Backend template rendering is the most CPU consumption of the reconciliation process, so sharding backends reduces haproxy ingress processing on workloads with thousands of services. Once sharding, haproxy ingress can update only the shards whose backends were changed since the last update.
When a full reconciliation happens, usually triggered by changing a global config, all the resources need to be parsed again, and this happen by clearing the state and building it again from scratch. This building process clears old states, removing from the controller the ability to find shards that had backends and doesn't have anymore. Since the file continues on the disk, the backend is registered on HAProxy, although it's not referenced anymore.
This is likely not to happen with ingress resources …
=> Fix shard render when the last backend is removed

pkg/converters/ingress/annotations/backend_test.go, pkg/converters/ingress/annotations/validator.go
Wildcard is a valid cors allowed header option, but validation wasn't allowing to configure it.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Headers
=> Add wildcard as a valid cors allowed header

builder/Dockerfile, rootfs/Dockerfile
See: https://www.haproxy.org/download/2.4/src/CHANGELOG
=> [release-0.13] Bump haproxy 2.4.24

.github/workflows/build.yaml, builder/Dockerfile, rootfs/Dockerfile
https://www.haproxy.org/download/2.4/src/CHANGELOG
go1.19.11 (released 2023-07-11) includes a security fix to the net/http package, as well as bug fixes to cgo, the cover tool, the go command, the runtime, and the go/printer package. See the [Go 1.19.11 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.19.11+label%3ACherryPickApproved) on our issue tracker for details.
go1.19.12 (released 2023-08-01) includes a security fix to the crypto/tls package, as well as bug fixes to the assembler and the compiler. See the [Go 1.19.12 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.19.12+label%3ACherryPickApproved) on our issue tracker for details.
=> [release-0.14] Bump 2.4.24

builder/Dockerfile, rootfs/Dockerfile
Tiny bump to the patch version of core haproxy due to [CVE-2023-40225](https://ubuntu.com/security/CVE-2023-40225).
* https://ubuntu.com/security/notices/USN-6294-1 
* http://git.haproxy.org/?p=haproxy-2.6.git;a=commit;h=d17c50010d591d1c070e1cb0567a06032d8869e9
=> bump haproxy to patch 2.6.15 for security vuln.

.github/dependabot.yml
Add a configuration for [dependabot](https://docs.github.com/en/code-security/dependabot) to help updating dependencies.
=> .github: Add dependabot configuration

pkg/haproxy/instance_test.go, rootfs/etc/templates/haproxy/haproxy.tmpl
When a backend response contains multiple values for the Vary header, like "Vary: header1, header2", the resulting Vary header response from haproxy is : "Vary: header2, Origin".
This is linked to this PR : #861
The official documentation states that `req.hdr` (or `res.hdr`) returns "only the last comma-separated value of the header".
So it should be `res.fhdr` instead.
=> Keep all vary header values when adding Origin

pkg/haproxy/instance_test.go, rootfs/etc/templates/haproxy/haproxy.tmpl
This is a fix for #1085 
The snippet used in the fix was provided by the issue's op (@tomklapka)
It uses txn.coraza.action instead of the txn.coraza.fail and allow for a more fine grained control about how requests should be rejected and fixes the issue that with the current coraza version all requests are rejected (txn.coraza.fail is most likely not set anymore).
I've based this fix of 0.14 because I wasn't able to get master running in our testing environment. Please let me know if I need to change anything here.
=> fix coraza configuration to use the action variable

builder/Dockerfile, rootfs/Dockerfile
HAProxy Ingress starts now as the non privileged user haproxy, and this is the same user that starts the embedded haproxy process. Some container runtimes do not configure the unprivileged_port_start param from the default 1024 to 0, which makes the embedded haproxy process fail to bind to 80/443 ports. Adding the net bind capability to the haproxy binary allows it to bind to any tcp port, without running as a privileged user, and without configuring unprivileged_port_start param.
=> Add net bind capability to haproxy bin

docs/haproxy-ingress.yaml, docs/static/resources/haproxy-ingress.yaml, examples/rbac/README.md, examples/rbac/ingress-controller-rbac.yml
Same change as done in the helm chart:
https://github.com/haproxy-ingress/charts/pull/58
=> Update RBAC configuration and docs to include leases resource for leader election

pkg/converters/ingress/annotations/global.go, pkg/haproxy/config.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/host.go, pkg/haproxy/types/types.go, rootfs/etc/templates/haproxy/haproxy.tmpl, tests/framework/options/objects.go, tests/integration/integration_test.go
`app-root` config key configures the root path redirect in haproxy frontend. https redirect however is configured in the backend. Because of that haproxy is redirecting from the root path to the application path in plain http, before redirecting to https. This is not a good approach because it makes security scanners infer that the application does not have a secure proxy.
This update adds a https redirect before the application redirect, in the case the root path of the host renders its ssl-redirect to true.
=> Ensure https redirect happens before root redirect

pkg/converters/ingress/annotations/backend.go, pkg/converters/ingress/annotations/backend_test.go, pkg/converters/ingress/annotations/mapper.go
Some configuration keys were not designed to be made from global due to the lack of a namespace name. Secure backend needs a namespace to read secrets for a CA bundle and client certificate. This update allows to provide a secret in the global ConfigMap by adding the namespace along with the name of the secret.
=> Allows secure backend configuration from global

pkg/converters/ingress/annotations/backend.go, pkg/converters/ingress/annotations/backend_test.go, pkg/converters/ingress/annotations/host.go, pkg/converters/ingress/annotations/mapper.go
Adds the option to configure auth-url globally. Global configurations don't rely on a namespace name, so the only change in the configuration is that a service url needs to add the namespace of the service when configured globally.
=> Allows to configure auth-url globally

docs/content/en/docs/configuration/command-line.md, pkg/controller/config/options.go
Master worker mode has a better process handling, more config key options, and should be the option if the user doesn't have a reason to choose the standalone daemon.
=> Change default master-worker config to true

Makefile, README.md, pkg/controller/services/svcleader.go, pkg/controller/services/svcstatusing.go
Building local image in the same arch of the host. This avoids the need of running under an emulator on m1/arm envs.
Minor updates on comments and public methods as well.
=> Local building improvements

docs/content/en/docs/configuration/keys.md
Add info on how to configure HAProxy to log to stdout.
Remove the line with v0.14 related info when merging to older versions.
=> doc: add haproxy logging to stdout

builder/Dockerfile, pkg/haproxy/instance.go, rootfs/Dockerfile
The embedded haproxy process is being created in the same pid group of the controller, which makes it receive the same signals received by the controller when running under a process supervisor. This makes haproxy be prematurely terminated when the controller is still shutting down.
=> Move embedded haproxy process to a distinct pid group

pkg/haproxy/config.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/types.go, rootfs/etc/templates/haproxy/haproxy.tmpl, tests/integration/integration_test.go
SNI maps were incorrectly used to match requests on ancient versions of HAProxy Ingress - v0.4 or so. A separated group of match files were being used since then on TLS based authentication configurations. We don't need it anymore, since all the mTLS configurations don't depend on the maps, so we're now dropping its support. Moreover, having a distinct group of match files leads to misbehavior depending on the configurations: a host and path with lower priority should be chosen if the one with more priority is added in the sni maps.
There is one behavior change with this update: a missing or misconfigured host header, for an ingress with mTLS, with optional certificate, without sending a certificate, would fallback to SNI in order to try a match. Now, since only the host header is the …
=> Remove dedicated maps for SNI match

.github/workflows/build.yaml, Makefile
Configures an integration test matrix for:
* minimum, latest and currently embedded haproxy versions
* oldest and latest Kubernetes versions
=> configure test matrix for haproxy and kubernetes

pkg/controller/services/svcleader.go, pkg/controller/services/svcstatus.go, tests/framework/framework.go
Leader election is designed to attempt leading just once. It will finish in the case it was elected the leader and for any reason couldn't update the lease resource. This update starts a for-loop, making the leader election to be restart in the case it is not leading anymore.
=> keep restarting leader election

pkg/converters/gateway/gateway.go, pkg/converters/gateway/gateway_test.go, pkg/converters/helper_test/cachemock.go
Existing gateway resources that does not have a valid gateway class - either by being non existent or not matching haproxy ingress, will neither return an error not return a valid instance, but instead nil,nil from the cache. We're checking for nil before trying to use the gw, but since we're assigning a nil pointer to a struct into an interface var, we cannot simply check for our `var == nil`:
https://go.dev/doc/faq#nil_error
=> fix panic if gw does not have a valid class

pkg/converters/gateway/gateway.go, pkg/haproxy/types/host.go, pkg/haproxy/types/types.go
Ingress and Gateway data are converted to haproxy frontend and backend data via their converter implementations. Some configurations need data from both sides, so frontend is linked to backend via a pathlink object. A pathlink has path specific data, as well as the ID of the backend it represents. A pointer from the pathlink to the ModeTCP field in the backend, along with a backend data substitution used by shard mode, were contributing to preserve old representations of a backend in memory, depending on the type of the changes made to gateway resources.
This update breaks the link between a new resource and an old backend representation, which fixes the memory leak.
=> fix memory leak on gateway reconciliation

docs/content/en/docs/configuration/command-line.md, pkg/controller/config/config.go, pkg/controller/config/options.go, pkg/controller/legacy/controller.go, pkg/controller/reconciler/reconciler.go, pkg/controller/services/services.go, pkg/controller/services/svcacme.go, pkg/haproxy/instance.go, pkg/haproxy/instance_test.go, pkg/main.go, pkg/utils/queue.go, tests/framework/framework.go
HAProxy Ingress does not use to restart a failed operation because the majority of the failed operations come from misconfiguration, so the configuration fix itself will make the retry.
Former HAProxy Ingress had only embedded and non master-worker mode, so other failures despite misconfigurations would be resource constraint related, like disk space, or bugs in haproxy or controller. Since master-worker mode and external haproxy, other sort of failures might happen, like connection refused to the admin socket. Because of that, a retry operation becomes mandatory, avoiding healthy but outdated load balancer config.
=> retry reload haproxy if failed

docs/content/en/docs/examples/metrics.md, docs/content/en/docs/examples/metrics/haproxy-ingress-dashboard.json, docs/content/en/docs/getting-started/_index.md, pkg/controller/services/svchealthz.go
improve metrics doc and configuration
* Update documentation
* Link metrics page in the getting started
* Add process collector metrics
* Improve dashboard compatibility and cpu display
* Changed the panel for displaying CPU usage to specifically select HAProxy Ingress job
* Flexibe hostname label filter for deployments without it
=> improve metrics doc and configuration

pkg/converters/gateway/gateway.go, pkg/converters/gateway/gateway_test.go, pkg/haproxy/types/backend.go, pkg/haproxy/types/backend_test.go
Gateway API allows to assign distinct backend refs behind the same hostname and path match. These refs can reference the same service, or even distinct services to the same endpoint. Gateway converter were using the same approach from ingress, by acquiring an existing endpoint if it exists, which end up of old ref configurations being overwritten by newer ones, if there is an endpoint duplication. This update changes this behavior, now every new backend ref entry will have a new set of endpoint entries in the backend, despite of these endpoints exist or not.
Fixes #1182
=> add endpoints even if duplicated

pkg/controller/legacy/cache.go, pkg/controller/legacy/controller.go, pkg/controller/services/cache.go, pkg/controller/services/ssl.go, pkg/converters/gateway/gateway.go, pkg/converters/gateway/gateway_test.go, pkg/converters/helper_test/cachemock.go, pkg/converters/ingress/ingress.go, pkg/converters/types/interfaces.go, tests/framework/framework.go, tests/framework/options/request.go, tests/framework/ssl.go, tests/integration/integration_test.go
I've implemented an heuristic to provide basic support for multiple certificates. It just works in my use case.
Please consider merging this change.
Thanks
=> allow multiple certificates

pkg/haproxy/instance.go
HAProxy could be started more than once in the case the very first start fails. Changing `up` check to `sync.Once` ensures that the proxy starts just once.
Should be added to v0.15 and v0.14 branches
=> ensure that embedded haproxy starts just once

pkg/controller/config/options.go, tests/framework/framework.go
Endpoints api is being deprecated on k8s 1.33, moving to EndpointSlice by default on v0.15, all the Endpoints references should be dropped from controller on v0.16.
Should be added to v0.15 branch.
=> move to endpointslice by default

pkg/controller/reconciler/watchers.go, pkg/converters/gateway/gateway_test.go, pkg/converters/helper_test/cachemock.go, pkg/converters/ingress/ingress_test.go, pkg/converters/tracker/tracker.go, pkg/converters/types/interfaces.go
Change tracking used to happen on distinct fields, one per resource type. Since v0.13 a single field receives all change tracking, and former fields were being used mostly on unit tests. We're now removing such old tracking fields and refactoring unit tests accordingly.
=> remove fields used by the former tracking

.golangci.yml, docs/content/en/docs/configuration/command-line.md, pkg/controller/config/config.go, pkg/controller/config/options.go, pkg/controller/reconciler/watchers.go, pkg/controller/services/cache.go, pkg/controller/services/services.go, pkg/converters/configmap/tcpservices.go, pkg/converters/configmap/tcpservices_test.go, pkg/converters/gateway/gateway.go, pkg/converters/gateway/gateway_test.go, pkg/converters/helper_test/cachemock.go, pkg/converters/helper_test/k8sobjects.go, pkg/converters/ingress/ingress.go, pkg/converters/ingress/ingress_test.go, pkg/converters/types/interfaces.go, pkg/converters/types/options.go, pkg/converters/utils/services.go, pkg/converters/utils/services_test.go, tests/framework/framework.go
remove all references to v1.Endpoints api, since it is deprecated on Kubernetes 1.33. `--enable-endpointslices-api` command-line option now is deprecated as well and noop.
=> deprecate v1.endpoints api

pkg/controller/config/config.go, pkg/controller/services/svcleaderrecorder.go, pkg/controller/services/svcstatusing.go, tests/framework/framework.go
A number of configurations require controller pod name and/or namespace configured, starting to become harder to add and maintain all the validations. We're configuring it mandatory now, since it is easy to automate this configuration and default Helm chart already configures it by default.
Need to add to the breaking backward compatibility list of v0.16.
=> makes controller pod namespace and name mandatory

pkg/controller/config/config.go, pkg/controller/services/svcstatusing.go, tests/framework/framework.go
HAProxy Ingress deployed outside a Kubernetes cluster does not have a pod name to provide. A missing pod name should be validated instead, and when missing, it should fail starting the controller only if using features that require its name. So we are changing pod name to optional again.
=> turn envvars optional

pkg/converters/ingress/annotations/mapper.go, tests/framework/framework.go, tests/framework/options/server.go, tests/integration/integration_test.go
TLS backend can be configured by adding a CA secret (verify server's certificate) and/or a Crt secret (server verify client's certificate). A former controller version was reading the namespace of a secret from the ingress that configures the annotation, leading to nil dereference when the value is configured globally. This was fixed by adding a new step, that verifies if the config is global or an annotation, and if the provided name has already a name or just the name of the secret.
This new step however broke the proto://content approach added on the get secret code because it happens before getting the secret, and the proto://content syntax is incompatible with the ns/name one. This failed deployments that read ca or crt from the file system.
Should be merged as far as v0.13.
=> fix reading backend ca certificate from file
