jcmoraisjr/haproxy-ingress

pkg/controller/template.go, rootfs/etc/haproxy/template/haproxy.tmpl
@jcmoraisjr Here is an alternative solution to https://github.com/jcmoraisjr/haproxy-ingress/pull/31 that uses the conditionals.
=> Wildcard conditionals

rootfs/etc/haproxy/template/haproxy.tmpl, rootfs/usr/local/etc/haproxy/errors/503noendpoints.http
create a 503 frontend/backend to respond to the default backends that are sent by the ingress library.
=> 503 server to respond to 127.0.0.1:8181 backends

pkg/controller/config.go, pkg/controller/template.go, pkg/types/types.go, rootfs/etc/haproxy/template/haproxy.tmpl
=> Add support for server-alias annotation

README.md
Providing short description on server-alias annotation.
Additional PR for #43.
=> Add server-alias description

examples/deployment/README.md, examples/deployment/haproxy-ingress.yaml
This PR makes the default deployment a little bit more consistent (uses an extra namespace like most other examples).
=> Make docs more consistent

pkg/common/ingress/controller/controller.go, pkg/controller/controller.go, pkg/controller/dynconfig/dynconfig.go, pkg/controller/stats_socket.go, pkg/types/types.go
* breakdown dynconfig.ConfigBackends into smaller pieces
* merge weight and scaling dynamic checks and updates
* fix equality of backends
* set ip/port/weight when dynamically removing endpoints
* dynamically remove endpoint even if dynamic scaling is turned off
* v(2) logs
=> Improvements on dynamic updates

README.md, pkg/common/ingress/annotations/balance/main.go, pkg/common/ingress/controller/annotations.go, pkg/common/ingress/controller/controller.go, pkg/common/ingress/defaults/main.go, pkg/common/ingress/types.go, pkg/common/ingress/types_equals.go, pkg/controller/config.go, pkg/types/types.go, rootfs/etc/haproxy/template/haproxy.tmpl
Add a new balance-algorithm annotation
Implement #109
=> balance-algorithm annotation

README.md, pkg/common/ingress/annotations/connection/main.go, pkg/common/ingress/controller/annotations.go, pkg/common/ingress/controller/controller.go, pkg/common/ingress/types.go, pkg/common/ingress/types_equals.go, pkg/controller/config.go, pkg/types/types.go, rootfs/etc/haproxy/template/haproxy.tmpl
Adding annotations and configmap option to configure connection limits and timeout to backend servers.
=> Connection limits and timeout config

README.md, pkg/common/ingress/annotations/snippet/main.go, pkg/common/ingress/annotations/snippet/main_test.go, pkg/common/ingress/controller/annotations.go, pkg/common/ingress/controller/controller.go, pkg/common/ingress/types.go, pkg/common/ingress/types_equals.go, rootfs/etc/haproxy/template/haproxy.tmpl
Add frontend and backend configuration snippet.
Implements #82
=> WIP: Add backend configuration snippet

rootfs/etc/haproxy/template/haproxy.tmpl
Show shasum of CA file in the template instead of the filename.
=> Show CA-PEM checksum

pkg/common/ingress/controller/controller.go
Create a backend context used to annotate spec/rules as well as spec/backend services.
Implements #134
=> Add backend annotations on ing.spec.backend

pkg/common/ingress/controller/controller.go
Add default HSTS configuration on default backend/location
Fix #171
=> Add HSTS on default backend

pkg/common/ingress/controller/controller.go
There are two ways to break HAProxy config with invalid http port configurations. This change fixes both:
* Using the same port on ssl-passthrough (https) and http: HAProxy would be configured to send http content to a tcp backend
* Using a port without a single active endpoint - zero replicas or referencing and invalid port: backends with no active endpoints are removed from the configuration and HAProxy would be configured to use a backend that doesn’t exist
=> Add ssl-passthrough-http-port validations

pkg/common/ingress/controller/controller.go
=> Fix panic if an invalid path is used on ssl-passthrough

docs/haproxy-ingress.yaml, examples/auth/basic/README.md, examples/daemonset/README.md, examples/daemonset/haproxy-ingress-daemonset.yaml, examples/deployment/haproxy-ingress.yaml, examples/scaling-deployment/README.md, examples/scaling-deployment/haproxy-ingress-deployment.yaml
Signed-off-by: Ricardo Pchevuzinske Katz <ricardo.katz@serpro.gov.br>
This PR improves some Docs, as reported in the following issues:
Fixes: #105 #253 #263 
The livenessProbe issue needs to be tested, as I wasn't able to test them right now.
=> Improve some docs

pkg/common/ingress/controller/controller.go
Discovered a bug where services with a named targetPort would end up with the port set to 0 in the haproxy config when drain support is on and the pod is terminating. This is because the port could not be converted to an int and instead needs to be retrieved by name from the pod's containers' ports.
Please cherry-pick back to release-0.6 and release-0.7 so it's included in any future bug fix releases from those branches.
=> Fix port retrieval for terminatingPod with named targetPort.

pkg/haproxy/instance_test.go, rootfs/etc/haproxy/template/haproxy.tmpl
=> Add custom-frontend to snippet to http:80 frontend

pkg/utils/queue.go, pkg/utils/queue_test.go
A work queue process jobs on an event loop. This improvement adds support to jobs that need to be enqueued again if an error occurs. Jobs that failed are re-enqueued after a configurable amount of time, which will grow exponentially (base 2) after new consecutive failures.
=> Add failure rate limit on work queue

Makefile
use GOARCH var to change the architecture, eg GOARCH=arm
=> customizeable goarch

docs/content/en/docs/configuration/command-line.md, docs/content/en/docs/configuration/keys.md, pkg/converters/ingress/defaults.go, pkg/haproxy/instance_test.go, rootfs/Dockerfile, rootfs/etc/haproxy/template/haproxy.tmpl
Update also the configuration template in order to remove config parsing warnings
=> Update to haproxy 2.0.11

pkg/acme/signer.go, pkg/acme/signer_test.go, pkg/haproxy/instance.go
Adjust text and verbosity of certificate sign logs
=> improve certificate sign logs

pkg/acme/x/acme/acme.go, pkg/common/ingress/controller/controller.go, pkg/common/ingress/controller/status_test.go, pkg/main.go
=> Sorting imports and code linting

pkg/converters/ingress/annotations/backend_test.go, pkg/converters/ingress/annotations/host.go, pkg/converters/ingress/ingress.go, pkg/converters/ingress/ingress_test.go, pkg/haproxy/config.go, pkg/haproxy/config_test.go, pkg/haproxy/dynupdate.go, pkg/haproxy/dynupdate_test.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/backends.go, pkg/haproxy/types/backends_test.go, pkg/haproxy/types/types.go, rootfs/etc/haproxy/template/haproxy.tmpl
Create a dedicated entity to implement backend related logic.
=> Move backend data and funcs to its own entity

pkg/converters/ingress/annotations/host.go, pkg/haproxy/config.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/host.go, pkg/haproxy/types/types.go, rootfs/etc/haproxy/template/haproxy.tmpl
A few small optimizations when needed to iterate through host or backend lists.
=> Small optimizations

pkg/converters/ingress/annotations/backend.go, pkg/converters/ingress/annotations/backend_test.go, pkg/converters/ingress/annotations/mapper_test.go
Simplify code as suggested by `gofmt`.
=> Follow gofmt convention

docs/content/en/docs/configuration/keys.md
Had me looking at my config map crazy
=> Typo on configuration keys docs

docs/content/en/docs/configuration/keys.md, pkg/converters/ingress/annotations/global.go, pkg/converters/ingress/annotations/host.go, pkg/converters/ingress/annotations/host_test.go, pkg/converters/ingress/annotations/updater.go, pkg/converters/ingress/defaults.go, pkg/converters/ingress/types/annotations.go, pkg/converters/ingress/types/global.go, pkg/haproxy/config.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/types.go
This is for https://github.com/jcmoraisjr/haproxy-ingress/issues/573
So far I only implemented the ciphers list, I'm planning to do add the generic bind-options as well but I wanted to do a quick feedback loop to verify if I'm going in the right direction and/or if I'm missing some stuff. I saw the todo about the template, but I'm not sure it's worth it, so I went with an approach I think is good enough and scalable for what it needs to do.
=> Host scoped cipher options

pkg/controller/cache.go, pkg/converters/ingress/ingress.go, pkg/converters/types/interfaces.go
log the object name(s) that started the ingress parsing.
=> log changed objects

.github/workflows/ci.yaml
Duplicate the Build and Test travis actions to Github Actions.
=> Duplicate Travis CI to Github Actions

pkg/converters/ingress/annotations/backend.go, pkg/converters/ingress/annotations/backend_test.go, pkg/haproxy/instance_test.go, rootfs/etc/lua/auth-request.lua
Now the script is a copy/paste from the source. The new version implements a simplified glob pattern to Lua pattern conversion, so we need to adapt the controller along with the script itself.
=> Update auth-request.lua script

pkg/haproxy/dynupdate.go, pkg/haproxy/dynupdate_test.go
The controller maintain and evolve an in memory model that reflects the haproxy state. This model is used to rebuild the configuration files and also to name haproxy backends and servers when running a dynamic update. If for any reason the model and the haproxy instance loose their synchronization, backends or servers might not be found and a dynamic update would fail. This update parses the haproxy response, if it returns a `No such server` or any other non recognized message, haproxy will be fully reloaded in order to resynchronize with the model.
=> Reload haproxy if a backend server cannot be found

pkg/haproxy/instance.go
Improves the visibility of a configuration issue. Currently only reload attempts would lead to a log error if the current state builds an invalid configuration file. This change adds an error log on every reconciliation, being dynamic or not, informing the timestamp when the configuration was broken for the first time, if the configuration is in fact broken. A broken configuration leads to new state not being correctly applied, and should also promote an outage if the controller or haproxy crashes, or the controller restarts.
=> Add log of reload error on every reconciliation

.github/workflows/image.yaml
=> Add arm64 build

.github/workflows/build.yaml, .golangci.yml, pkg/acme/server.go, pkg/acme/x/acme/acme.go, pkg/acme/x/acme/jws_test.go, pkg/acme/x/acme/types.go, pkg/common/ingress/controller/backend_ssl.go, pkg/common/ingress/controller/launch.go, pkg/common/ingress/controller/status.go, pkg/controller/cache.go, pkg/converters/gateway/gateway_test.go, pkg/converters/helper_test/cachemock.go, pkg/converters/ingress/annotations/backend.go, pkg/converters/ingress/annotations/backend_test.go, pkg/converters/ingress/annotations/global.go, pkg/converters/ingress/annotations/mapper.go, pkg/converters/ingress/ingress.go, pkg/converters/ingress/ingress_test.go, pkg/haproxy/dynupdate.go, pkg/haproxy/instance.go, pkg/haproxy/instance_test.go, pkg/haproxy/socket/socket_test.go, pkg/haproxy/types/backends.go, pkg/haproxy/types/maps.go, pkg/utils/queue_test.go, pkg/utils/utils.go
This enables a couple of linters on https://github.com/golangci/golangci-lint and includes it in the github action pipeline.
Feel free to enable more linters at a later point.
=> Add golangci-lint and fix issues found by it

.github/workflows/image.yaml
Add target platform images for `linux/arm/v7`, `linux/arm/v6` and `linux/s390x`.
=> Add new target platforms

.gitignore, Makefile, README.md, docs/content/en/docs/configuration/command-line.md, pkg/common/ingress/controller/controller.go, pkg/common/ingress/controller/launch.go, pkg/common/ingress/types.go, pkg/controller/controller.go, pkg/converters/ingress/annotations/global.go, pkg/converters/ingress/annotations/updater.go, pkg/converters/types/options.go, pkg/haproxy/config.go, pkg/haproxy/instance.go, pkg/haproxy/types/types.go, rootfs/etc/templates/haproxy/haproxy.tmpl, rootfs/haproxy-reload.sh, rootfs/haproxy-shutdown.sh
Add Makefile command and controller option that allows to run the controller outside of a container. These options are specially useful to develop and test locally.
=> Add local deployment configuration

Makefile
Ran succesfully 
make test
make docker-build
=> Fix docker-build target name

pkg/common/net/ssl/ssl.go
HAProxy Ingress v0.14 and older starts as root by default and create files as 0600 that should be read by HAProxy. When HAProxy runs as a sidecar and stars as non root (default since its 2.4) it won't have permission to read those files. This update makes files generated as 0600 (crt/key) having its owner to PID 99, which's the PID used by HAProxy containers.
=> Change owner of crt/key files to haproxy pid

pkg/common/ingress/controller/launch.go, pkg/controller/config/config.go, pkg/controller/reconciler/watchers.go, pkg/controller/services/services.go
Add EndpointSlice API on v0.15 handler.
=> Add endpointslice api on v0.15 handler

docs/content/en/docs/configuration/keys.md, pkg/controller/reconciler/watchers.go, pkg/converters/gateway/gateway_test.go, pkg/converters/helper_test/marshal.go, pkg/converters/ingress/annotations/host.go, pkg/converters/ingress/ingress.go, pkg/converters/ingress/ingress_test.go, pkg/haproxy/instance.go, pkg/haproxy/instance_test.go, pkg/haproxy/types/tcpservices.go, pkg/haproxy/types/types.go, rootfs/etc/templates/crtlist/crtlist.tmpl, rootfs/etc/templates/haproxy/haproxy.tmpl, tests/framework/framework.go, tests/framework/options/objects.go, tests/framework/options/request.go, tests/integration/integration_test.go
Add the ability to configure more than one server certificate on TCP services.
=> Support list of server crt on tls tcp service

pkg/controller/reconciler/reconciler.go, pkg/controller/reconciler/watchers.go, pkg/utils/workqueue/ratelimiters.go
Use a custom type in the reconciler, since haproxy ingress does not rely on the namespace/name of the resource being changed. A custom type allows to send parameters used by the controller.
=> change reconciler to a custom type

pkg/haproxy/instance.go
master socket based reloads happen by issuing a reload command to haproxy, which will fork a new process for the new configuration. This process happens asynchronously, so there is an unexpected but possible chance to talk with master via its socket before the reload starts.
HAProxy Ingress expects haproxy properly reflecting its internal model, because of that it needs to wait for the reload to finish, otherwise dynamic updates should fail due to outdated data.
This update adds a new check on this process: whenever a reload is going to happen, the number of reloads is copied, and haproxy ingress will continue to wait until it is incremented.
Should be added to v0.15 and v0.14 branches
=> check if haproxy reloaded already
